Repository qri-io/qri, pull requests merged in 2018-03, with the labels that each got.

#288 feat: (WIP) color diff output
  api/server_test.go
  api/testdata/addRequestFromURL.json
  api/testdata/addResponseFromURL.json
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/listResponse.json
  api/testdata/renameResponse.json
  cmd/diff.go
  cmd/print.go
  core/datasets_test.go
  repo/test/test_repo.go
  repo/test/testdata/archive.cdxj
  repo/test/testdata/archive.json
Labels: in progress

#289 chore: update references to datasetDiffer to dsdiff
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  Makefile
  cmd/diff.go
  core/datasets.go
  core/datasets_test.go
Labels: in progress

#280 WIP - feat(api): updates to API for webapp
  Makefile
  api/config.go
  api/datasets.go
  api/middleware.go
  api/root.go
  api/server.go
  api/server_test.go
  api/templates.go
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  api/testdata/diffResponse.json
  api/testdata/diffResponsePlusMinusColor.json
  api/testdata/historyResponse.json
  api/testdata/listResponse.json
  api/testdata/saveMetaRequest.json
  api/testdata/saveMetaResponse.json
  api/transports.go
  cmd/connect.go
  cmd/diff.go
  core/datasets.go
  core/datasets_test.go
  logging/logging.go
  repo/test/test_repo.go
  repo/test/testdata/cities/data.csv
  repo/test/testdata/cities/input.dataset.json
  repo/test/testdata/counter/data.csv
  repo/test/testdata/counter/input.dataset.json
  repo/test/testdata/craigslist/data.json
  repo/test/testdata/craigslist/expect.dataset.json
  repo/test/testdata/craigslist/input.dataset.json
  repo/test/testdata/movies/data.csv
  repo/test/testdata/movies/input.dataset.json
Labels: in progress

#295 feat(private flag): add private flag to cli and api add
  api/datasets.go
  api/server_test.go
  api/testdata/addResponsePrivate.json
  cmd/add.go
  core/datasets.go
Labels: feat, in progress

#296 feat(CBOR): addex experimental support for CBOR data format
  .circleci/cover.test.sh
  Dockerfile
  Makefile
  api/datasets.go
  api/peers.go
  api/server.go
  api/server_test.go
  api/testdata/listResponse.json
  cmd/add.go
  cmd/cmd_test.go
  cmd/data.go
  cmd/export.go
  cmd/setup.go
  codecov.yml
  core/datasets.go
  core/datasets_test.go
  core/params.go
  p2p/message_test.go
  repo/profile/profile.go
  repo/test/test_repo.go
  repo/test/testdata/flourinated_compounds_in_fast_food_packaging/data.cbor
  repo/test/testdata/flourinated_compounds_in_fast_food_packaging/input.dataset.json
Labels: in progress

#299 feat(webapp): fetch webapp hash via dnslink
  api/config.go
  api/server.go
  core/self_update.go
  core/self_update_test.go
Labels: in progress

#298 feat(PeerID): add PeerID to datasetRef
  api/context.go
  api/context_test.go
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/listResponse.json
  api/testdata/profileResponse.json
  cmd/list.go
  core/datasets.go
  core/datasets_test.go
  core/history_test.go
  repo/fs/refstore.go
  repo/ref.go
  repo/ref_test.go
  repo/repo.go
  repo/test/test_refstore.go
  repo/test/test_repo.go
Labels: feat, in progress

#300 fix(DatasetRef): fixes to datasetRef handling, add back connect endpoint
  api/peers.go
  api/server.go
  api/server_test.go
  core/datasets.go
  core/peers.go
  repo/fs/peer_store.go
  repo/fs/refstore.go
Labels: in progress

#303 fix(*): update to allow hashes, and fix bugs that PeerID introduced
  api/datasets.go
  api/history.go
  api/root.go
  api/server_test.go
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  api/testdata/diffResponse.json
  api/testdata/diffResponsePlusMinusColor.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/removeResponseByPath.json
  api/testdata/removeResponseWithPath.json
  core/datasets.go
  core/history.go
  repo/fs/refstore.go
  repo/ref.go
  repo/ref_test.go
  repo/test/test_refstore.go
Labels: in progress

#306 fix(Validate): completely overhaul validation to make it work properly
  api/server_test.go
  api/testdata/addResponseFromURL.json
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  api/testdata/diffResponse.json
  api/testdata/diffResponsePlusMinusColor.json
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/removeResponseByPath.json
  api/testdata/removeResponseWithPath.json
  api/testdata/renameResponse.json
  api/testdata/saveMetaResponse.json
  cmd/add.go
  cmd/save.go
  core/datasets.go
  core/datasets_test.go
  core/profile.go
  repo/test/testdata/craigslist/input.dataset.json
Labels: in progress

#305 fix(data api endpoint): need path in response to be able to normalize…
  api/datasets.go
  api/server.go
Labels: in progress

#307 chore(codeclimate): add initial codeclimate configuration
  .codeclimate.yml
Labels: in progress

#309 chore(release): release 0.2.0
  CHANGELOG.md
  api/config.go
  cmd/version.go
Labels: in progress

#311 fix(structuredData): data should return DataPath not dataset Path
  api/datasets.go
  core/datasets.go
Labels: bug, in progress

#315 refactor(memfs): update to match memfs merge into cafs
  api/datasets.go
  cmd/connect.go
  core/core_test.go
  core/datasets.go
  core/datasets_test.go
  core/profile.go
  p2p/node_test.go
  repo/fs/fs_test.go
  repo/graph_test.go
  repo/ref_test.go
  repo/test/test_datasets.go
  repo/test/test_refstore.go
  repo/test/test_repo.go
Labels: in progress

#320 refactor(logs): plumb initial log instrumentation repo-wide
  api/config.go
  api/datasets.go
  api/history.go
  api/middleware.go
  api/peers.go
  api/profile.go
  api/server.go
  cmd/connect.go
  cmd/repo.go
  core/core.go
  core/datasets.go
  core/history.go
  core/peers.go
  core/profile.go
  core/search.go
  core/self_update.go
  logging/logging.go
  main.go
  p2p/bootstrap.go
  p2p/config.go
  p2p/datasets.go
  p2p/handlers.go
  p2p/logging.go
  p2p/message.go
  p2p/node.go
  p2p/p2p.go
  p2p/peers.go
  repo/fs/analytics.go
  repo/fs/change_requests.go
  repo/fs/datasets.go
  repo/fs/files.go
  repo/fs/fs.go
  repo/fs/peer_store.go
  repo/fs/query_logs.go
  repo/fs/refstore.go
Labels: in progress

#321 Added troubleshooting.md and updated README.md to link to it
  README.md
  troubleshooting.md
Labels: docs

#323 feat(read-only): add read-only mode to qri server
  api/config.go
  api/datasets.go
  api/middleware.go
  api/peers.go
  api/profile.go
  api/server.go
  api/server_test.go
  cmd/connect.go
Labels: feat, in progress

#324 refactor(profile.ID) adding peer / profile ID distinctions
  api/datasets.go
  api/peers.go
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/profileResponse.json
  api/testdata/removeResponseByPath.json
  api/testdata/removeResponseWithPath.json
  api/testdata/saveMetaResponse.json
  cmd/connect.go
  cmd/connections.go
  cmd/list.go
  core/core_test.go
  core/datasets.go
  core/params.go
  core/peers.go
  core/peers_test.go
  core/profile.go
  core/schemas/profileSchema.json
  p2p/dataset.go
  p2p/datasets.go
  p2p/node.go
  p2p/node_test.go
  p2p/p2p_test.go
  p2p/peers.go
  p2p/profile.go
  p2p/profile_test.go
  repo/actions/dataset.go
  repo/actions/dataset_test.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/fs/profile_store.go
  repo/fs/refstore.go
  repo/graph_test.go
  repo/mem_repo.go
  repo/profile/id.go
  repo/profile/id_test.go
  repo/profile/profile.go
  repo/profile/store.go
  repo/profile/type.go
  repo/profile/type_test.go
  repo/profile/user_type.go
  repo/profiles.go
  repo/ref.go
  repo/ref_test.go
  repo/repo.go
  repo/test/test.go
  repo/test/test_dataset_actions.go
  repo/test/test_refstore.go
  repo/test/test_repo.go
  repo/test/testdata/config.yaml
Labels: in progress
