Repository qri-io/qri, pull requests merged in 2018-06, with the labels that each got.

#428 refactor(yaml): changes to make yaml our default format
  Makefile
  cmd/cmd_test.go
  cmd/config.go
  cmd/export.go
  config/config.go
  config/profile.go
  config/testdata/simple.yaml
  core/config.go
  repo/test/test_repo.go
Labels: in progress

#430 fix(cmd): changes to add, diff, and global config flag
  cmd/add.go
  cmd/print.go
  cmd/print_test.go
  cmd/root.go
  core/datasets.go
Labels: in progress

#432 refactor(datasets): Use Copy and PagedReader. Rename StructuredData.
  api/datasets.go
  cmd/data.go
  core/datasets.go
  core/datasets_test.go
Labels: in progress

#436 docs(cmd): add examples and fix docs on help page for CLI commands
  cmd/add.go
  cmd/diff.go
  cmd/remove.go
  cmd/rename.go
  cmd/save.go
  cmd/validate.go
Labels: in progress

#424 feat(skylark): Pass previous dataset body to skylark for updates
  repo/actions/dataset.go
  repo/actions/transform.go
Labels: in progress

#438 feat(cmd/export): specify data format using --data-format flag
  cmd/cmd_test.go
  cmd/export.go
  cmd/save.go
Labels: in progress

#439 feat(transform secrets): supply secrets to transforms
  cmd/add.go
  cmd/cmd.go
  cmd/print.go
  cmd/root.go
  cmd/save.go
  core/datasets.go
  repo/actions/dataset.go
  repo/actions/dataset_test.go
  repo/actions/transform.go
  repo/test/test_dataset_actions.go
  repo/test/test_repo.go
Labels: feat, in progress

#442 chore(transform): Copy util for handling output from transformation
  repo/actions/transform.go
Labels: in progress

#444 feat(registry cmd): add commands for working with registries
  cmd/add.go
  cmd/cmd_test.go
  cmd/registry.go
  cmd/repo.go
  cmd/save.go
  core/core.go
  core/core_test.go
  core/datasets.go
  core/registry.go
  repo/actions/dataset.go
  repo/actions/registry.go
Labels: feat, in progress

#445 feat(CreateDataset): write author ProfileID when creating a dataset
  api/server_test.go
  api/testdata/addResponseFromURL.json
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  api/testdata/diffResponsePlusMinusColor.json
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/removeResponseByPath.json
  api/testdata/removeResponseWithPath.json
  api/testdata/renameResponse.json
  api/testdata/saveMetaResponse.json
  repo/actions/dataset.go
Labels: feat, in progress

#446 docs(cmd/peers.go): add `format` flag, update docs/examples
  cmd/peers.go
  cmd/validate.go
Labels: in progress

#447 chore(release): release version 0.4.0
  CHANGELOG.md
  cmd/version.go
  p2p/p2p.go
Labels: chore, in progress

#451 refactor(schema): Replace schemaScanMode with TopLevelType.
  cmd/version.go
  core/render.go
  p2p/p2p.go
Labels: in progress

#452 fix(cmd/peers): fixing `network` flag bug
  cmd/list.go
  cmd/peers.go
  cmd/print.go
  config/readme.md
Labels: in progress

#454 refactor(cmd): overhaul cmd package
  cmd/add.go
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/config.go
  cmd/connect.go
  cmd/connect_test.go
  cmd/data.go
  cmd/diff.go
  cmd/export.go
  cmd/factory.go
  cmd/generate/generate.go
  cmd/info.go
  cmd/io.go
  cmd/list.go
  cmd/log.go
  cmd/peers.go
  cmd/print.go
  cmd/qri.go
  cmd/registry.go
  cmd/remove.go
  cmd/rename.go
  cmd/render.go
  cmd/repo.go
  cmd/root.go
  cmd/save.go
  cmd/search.go
  cmd/setup.go
  cmd/tutorials_test.go
  cmd/validate.go
  cmd/version.go
  core/config.go
  core/datasets.go
  core/setup.go
  p2p/node.go
Labels: in progress, refactor

#458 feat(export): export transform.sky when present
  cmd/cmd_test.go
  cmd/export.go
Labels: feat, in progress

#459 fix(config): set map values with config set command
  cmd/config.go
  config/config.go
  config/config_test.go
Labels: fix, in progress

#461 fix(CreateDataset): user-specified data should override transforms
  cmd/cmd_test.go
  cmd/connect_test.go
  cmd/print.go
  cmd/qri.go
  cmd/setup.go
  cmd/tutorials_test.go
  core/datasets_test.go
  core/testdata/tf/transform.sky
  repo/actions/dataset.go
Labels: fix, in progress

#460 feat(Search): added implementations for core search and command line search
  cmd/print.go
  cmd/qri.go
  cmd/search.go
  core/search.go
  core/search_test.go
Labels: in progress

#462 refactor(dataset.Body): rename dataset.Data to Body
  api/datasets.go
  api/server.go
  api/server_test.go
  api/testdata/addRequestFromURL.json
  api/testdata/addResponseFromURL.json
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/removeResponseByPath.json
  api/testdata/removeResponseWithPath.json
  api/testdata/renameResponse.json
  api/testdata/saveMetaResponse.json
  cmd/add.go
  cmd/body.go
  cmd/body_test.go
  cmd/cmd_test.go
  cmd/export.go
  cmd/qri.go
  cmd/save.go
  core/datasets.go
  core/datasets_test.go
  core/render.go
  core/testdata/cities_2/body.csv
  core/testdata/jobs_by_automation/body.csv
  core/testdata/jobs_by_automation_2/body.csv
  repo/actions/dataset_test.go
  repo/dataset.go
  repo/dataset_test.go
  repo/graph.go
  repo/test/test_dataset_actions.go
  repo/test/test_repo.go
  repo/test/testdata/cities/body.csv
  repo/test/testdata/counter/body.csv
  repo/test/testdata/craigslist/body.json
  repo/test/testdata/flourinated_compounds_in_fast_food_packaging/body.cbor
  repo/test/testdata/movies/body.csv
  repo/test/testdata/sitemap/body.json
Labels: in progress, refactor

#464 fix(list peer datasets): fix to make listing peer datasets work
  lib/datasets.go
Labels: fix, in progress

#465 feat(use, get): added use and get commands
  .circleci/config.yml
  cmd/body.go
  cmd/factory.go
  cmd/get.go
  cmd/qri.go
  cmd/use.go
  lib/datasets.go
  lib/history.go
  lib/lib.go
  lib/lib_test.go
  lib/render.go
  lib/selection.go
  lib/selection_test.go
  repo/actions/dataset_test.go
  repo/actions/select.go
  repo/fs/files.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/graph_test.go
  repo/mem_repo.go
  repo/ref.go
  repo/repo.go
  repo/test/test.go
  repo/test/test_dataset_actions.go
  repo/test/test_repo.go
Labels: feat, in progress

#467 chore(release): release v0.5.0
  CHANGELOG.md
  cmd/version.go
  p2p/p2p.go
Labels: chore, in progress

#473 fix(cmd): Wrap how DatasetRefs are parsed for better cmd behavior.
  cmd/add.go
  cmd/cmd.go
  cmd/remove.go
  cmd/save.go
Labels: in progress

#468 test(cmd): add tests for all cli commands
  cmd/add.go
  cmd/body.go
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/config.go
  cmd/connect.go
  cmd/diff.go
  cmd/export.go
  cmd/get.go
  cmd/info.go
  cmd/io.go
  cmd/list.go
  cmd/log.go
  cmd/peers.go
  cmd/print.go
  cmd/registry.go
  cmd/remove.go
  cmd/remove_test.go
  cmd/rename.go
  cmd/rename_test.go
  cmd/render.go
  cmd/render_test.go
  cmd/save.go
  cmd/save_test.go
  cmd/search.go
  cmd/search_test.go
  cmd/setup.go
  cmd/test_factory.go
  cmd/testdata/days_of_week.csv
  cmd/testdata/days_of_week_schema.json
  cmd/testdata/movies/body_ten.csv
  cmd/testdata/movies/body_twenty.csv
  cmd/testdata/movies/dataset.json
  cmd/testdata/template.html
  cmd/use.go
  cmd/use_test.go
  cmd/validate.go
  cmd/validate_test.go
  lib/datasets.go
  lib/error.go
  lib/error_test.go
  lib/render.go
  lib/render_test.go
Labels: in progress
