Repository qri-io/qri, pull requests merged in 2018-09, with the labels that each got.

#533 fix(api.Body): fix bug that returns error when getting a peers body
  api/datasets.go
Labels: in progress

#535 test(api): Fix api unit tests by updating responses and ipfs hashes
  api/server_test.go
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/newResponseFromURL.json
  api/testdata/removeResponseByPath.json
Labels: in progress

#536 fix(p2p): NewQriNode parameter cleanup, and factory for TestableQriNode.
  api/server.go
  api/server_test.go
  cmd/connect.go
  cmd/save_test.go
  cmd/setup.go
  cmd/test_factory.go
  config/profile.go
  lib/datasets_test.go
  lib/lib_test.go
  lib/peers_test.go
  lib/registry.go
  p2p/connected_test.go
  p2p/dataset_test.go
  p2p/datasets_test.go
  p2p/events_test.go
  p2p/node.go
  p2p/node_test.go
  p2p/peers_test.go
  p2p/ping_test.go
  p2p/profile_test.go
  p2p/test/p2ptest.go
Labels: in progress

#542 chore(deps): update gx deps
  Makefile
  actions/merge_events_test.go
  api/api.go
  api/testdata/api.snapshot
  cmd/connect.go
  cmd/qri.go
  config/p2p.go
  config/test/test_peers.go
  lib/lib.go
  lib/peers.go
  lib/self_update.go
  lib/self_update_test.go
  p2p/bootstrap.go
  p2p/connected.go
  p2p/datasets.go
  p2p/discovery.go
  p2p/events.go
  p2p/message.go
  p2p/node.go
  p2p/p2p.go
  p2p/peers.go
  p2p/ping.go
  p2p/profile.go
  p2p/profile_test.go
  p2p/profiles.go
  p2p/test/p2ptest.go
  p2p/wrapped_stream.go
  package.json
  repo/events.go
  repo/events_test.go
  repo/fs/profile_store.go
  repo/fs/profile_store_test.go
  repo/profile/id.go
  repo/profile/profile.go
  repo/profile/store.go
Labels: chore, in progress

#544 fix(CreateDataset): remove transform creating default viz
  actions/dataset.go
  actions/setup.go
  actions/setup_test.go
  actions/viz.go
  cmd/setup.go
  lib/setup.go
Labels: fix, in progress

#545 remove extra double quote
  Makefile
Labels: chore

#548 chore(release): release version 0.5.2
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: chore, in progress

#549 feat(p2p local streams): add local streams to QriNode for local stdio interaction
  .circleci/config.yml
  Makefile
  actions/transform.go
  api/testdata/api.snapshot
  cmd/qri.go
  lib/lib.go
  p2p/bootstrap.go
  p2p/discovery.go
  p2p/node.go
  p2p/p2p.go
Labels: in progress

#551 refactor(ioes): move cmd.IOStreams into separate package
  Makefile
  actions/dataset.go
  cmd/add.go
  cmd/body.go
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/config.go
  cmd/connect.go
  cmd/connect_test.go
  cmd/diff.go
  cmd/export.go
  cmd/factory_test.go
  cmd/generate/generate.go
  cmd/get.go
  cmd/get_test.go
  cmd/info.go
  cmd/io.go
  cmd/list.go
  cmd/log.go
  cmd/new.go
  cmd/peers.go
  cmd/print.go
  cmd/qri.go
  cmd/registry.go
  cmd/remove.go
  cmd/remove_test.go
  cmd/rename.go
  cmd/rename_test.go
  cmd/render.go
  cmd/render_test.go
  cmd/save.go
  cmd/save_test.go
  cmd/search.go
  cmd/search_test.go
  cmd/setup.go
  cmd/use.go
  cmd/use_test.go
  cmd/validate.go
  cmd/validate_test.go
  cmd/version.go
  docs/docs.go
  p2p/node.go
  repo/graph.go
  repo/graph_test.go
Labels: in progress, refactor

#552 feat(dry run): add dry-run flag to new & save dataset
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  actions/registry_test.go
  actions/select_test.go
  actions/transform_test.go
  api/dataset_test.go
  api/datasets.go
  api/testdata/api.snapshot
  cmd/new.go
  cmd/save.go
  lib/datasets.go
  lib/datasets_test.go
  lib/testdata/tf/transform.sky
Labels: feat, in progress

#553 chore(release): release version 0.5.3
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: chore, in progress
