Repository qri-io/qri, pull requests merged in 2018-05, with the labels that each got.

#372 test(core.Profile): testcase for SaveProfile
  core/profile.go
  core/profile_test.go
Labels: in progress

#376 refactor(infoCommand): make info command only work for datasets
  cmd/data.go
  cmd/info.go
  cmd/rename.go
Labels: in progress

#377 fix(setup): fix config not loading if already found
  cmd/connect.go
  config/api.go
Labels: in progress

#379 feat(api/config): refactor cmd/config.go and add api/config.go
  cmd/config.go
  config/api.go
  config/api_test.go
  config/cli.go
  config/cli_test.go
  config/config.go
  config/config_test.go
  config/logging.go
  config/logging_test.go
  config/p2p.go
  config/p2p_test.go
  config/profile.go
  config/profile_test.go
  config/registry.go
  config/registry_test.go
  config/repo.go
  config/repo_test.go
  config/rpc.go
  config/rpc_test.go
  config/store.go
  config/store_test.go
  config/webapp.go
  config/webapp_test.go
  core/config.go
  core/profile.go
  core/profile_test.go
Labels: in progress

#380 fix(SetProfile): peer should be able to remove name, email, descripti…
  core/profile.go
Labels: fix, in progress

#382 test(api): update api to match dataset commit signing changes
  api/server_test.go
  api/testdata/addResponseFromURL.json
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  api/testdata/diffResponse.json
  api/testdata/diffResponsePlusMinusColor.json
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/removeResponseByPath.json
  api/testdata/removeResponseWithPath.json
  api/testdata/renameResponse.json
  api/testdata/saveMetaResponse.json
Labels: in progress

#384 refactor(p2p): extract NewTestNetwork into its own p2ptest package
  core/core.go
  core/datasets.go
  p2p/events_test.go
  p2p/node.go
  p2p/node_test.go
  p2p/p2p_test.go
  p2p/ping_test.go
  p2p/profile_test.go
  p2p/test/p2ptest.go
  repo/test/test_repo.go
Labels: in progress

#385 test(api): add abide package and use to flesh out api handler tests for profile
  Makefile
  api/__snapshots__/api.snapshot
  api/profile_test.go
  api/testdata/addResponseFromURL.json
  api/testdata/diffResponse.json
  api/testdata/diffResponsePlusMinusColor.json
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/profileResponse.json
  api/testdata/removeResponseByPath.json
  api/testdata/removeResponseWithPath.json
  api/testdata/renameResponse.json
  api/testdata/saveMetaResponse.json
  core/profile.go
  repo/test/test_repo.go
Labels: in progress

#386 test(p2p): test for DatasetRequests.List over p2p
  core/datasets_test.go
  p2p/dataset_test.go
  p2p/datasets_test.go
  p2p/events_test.go
  p2p/node.go
  p2p/node_test.go
  p2p/p2p_test.go
  p2p/ping_test.go
  p2p/profile_test.go
  p2p/test/p2ptest.go
  repo/test/test_repo.go
Labels: in progress

#388 feat(p2p): transition to online-first peer display, p2p networking fixes, tag qri peers in p2p.ConnManager, merge "qri connections" command into "qri peers list"
  api/peers.go
  cmd/cmd_test.go
  cmd/connections.go
  cmd/peers.go
  cmd/print.go
  cmd/repo.go
  config/config.go
  config/config_test.go
  config/p2p.go
  config/profile.go
  config/profile_test.go
  core/datasets.go
  core/params.go
  core/peers.go
  core/peers_test.go
  p2p/bootstrap.go
  p2p/connected.go
  p2p/connected_test.go
  p2p/ipfs_nodes.go
  p2p/node.go
  p2p/p2p.go
  p2p/p2p_test.go
  p2p/peers.go
  p2p/peers_test.go
  p2p/profile.go
  p2p/profile_test.go
  p2p/wrapped_stream.go
  repo/actions/dataset.go
  repo/fs/profile_store.go
  repo/fs/profile_store_test.go
  repo/fs/testdata/simple.json
  repo/profile/profile.go
  repo/profile/store.go
Labels: feat, in progress

#387 refactor(CodingPattern): rename usage of CodingDataset to DatasetPod
  repo/ref.go
Labels: in progress

#389 feat(core.GetProfile): add naive online indicator if P2P is enabled
  api/__snapshots__/api.snapshot
  api/server_test.go
  api/testdata/profileResponse.json
  core/profile.go
  repo/profile/profile.go
Labels: feat, in progress

#390 feat(peer connections): single peer connection control
  api/peers.go
  cmd/connect.go
  cmd/diff.go
  cmd/peers.go
  cmd/search.go
  cmd/version.go
  core/peers.go
  p2p/peers.go
  repo/profile/store.go
Labels: feat, in progress

#391 fix(p2p.handleDatasetsList): peer's datasets now return fully hydrated
  p2p/datasets.go
Labels: in progress

#352 feat(repo): merge repos' EventLogs using a simple first attempt
  repo/actions/merge_events.go
  repo/actions/merge_events_test.go
  repo/events.go
Labels: in progress

#394 test(registry): switch to mock registery server package
  api/profile_test.go
  api/server_test.go
  cmd/cmd_test.go
  cmd/connect_test.go
  core/setup_test.go
Labels: in progress, test

#398 feat(render): add render command for executing templates against datasets
  api/server.go
  cmd/render.go
  cmd/repo.go
  config/config.go
  config/p2p.go
  config/render.go
  config/render_test.go
  config/testdata/default.yaml
  config/testdata/simple.yaml
  core/core.go
  core/core_test.go
  core/render.go
  core/render_test.go
  core/self_update.go
  core/self_update_test.go
  repo/actions/dataset.go
Labels: feat, in progress

#400 feat(registry.Datasets): initial dataset registry integration
  api/profile_test.go
  api/server_test.go
  cmd/cmd_test.go
  cmd/connect_test.go
  cmd/repo.go
  core/core_test.go
  core/datasets.go
  core/datasets_test.go
  core/history_test.go
  core/peers_test.go
  core/profile_test.go
  core/render_test.go
  core/search_test.go
  core/setup_test.go
  repo/actions/dataset.go
  repo/actions/dataset_test.go
  repo/actions/merge_events_test.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/graph_test.go
  repo/mem_repo.go
  repo/ref_test.go
  repo/repo.go
  repo/test/test_repo.go
Labels: feat, in progress

#404 refactor(p2p): remove p2p_test again
  p2p/connected_test.go
  p2p/node.go
  p2p/p2p_test.go
  p2p/peers_test.go
  p2p/test/p2ptest.go
Labels: in progress

#405 fix(registry): make registry post & deletes actually work
  cmd/remove.go
  cmd/repo.go
  core/datasets.go
  repo/actions/dataset.go
  repo/fs/fs.go
Labels: fix, in progress

#402 chore(release): release v0.3.2
  CHANGELOG.md
  cmd/version.go
  config/webapp.go
  p2p/p2p.go
Labels: chore, in progress

#406 test(p2p): test for DatasetRequests.Get using p2p test framework
  core/datasets.go
  core/datasets_test.go
  p2p/node_test.go
  p2p/test/p2ptest.go
  repo/test/test_repo.go
Labels: in progress

#413 perf(Add, Save): Overhaul Dataset Add & Save Methods
  api/__snapshots__/api.snapshot
  api/datasets.go
  api/peers.go
  api/server_test.go
  api/testdata/addRequestFromURL.json
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  api/testdata/diffResponse.json
  api/testdata/diffResponsePlusMinusColor.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/profileResponse.json
  api/testdata/removeResponseWithPath.json
  api/testdata/saveMetaResponse.json
  cmd/add.go
  cmd/cmd_test.go
  cmd/export.go
  cmd/list.go
  cmd/print.go
  cmd/save.go
  cmd/version.go
  core/datasets.go
  core/datasets_test.go
  core/profile.go
  core/profile_test.go
  core/testdata/cities_2/data.csv
  core/testdata/jobs_by_automation/data.csv
  core/testdata/jobs_by_automation_2/data.csv
  p2p/p2p.go
  repo/actions/dataset_test.go
  repo/dataset.go
  repo/dataset_test.go
  repo/fs/fs.go
  repo/graph.go
  repo/graph_test.go
  repo/repo.go
  repo/test/test_repo.go
  repo/testdata/schools.cbor
Labels: in progress, perf, refactor

#417 chore(cmd): go fmt recent changes
  cmd/add.go
  cmd/cmd_test.go
  cmd/export.go
  cmd/print.go
  repo/actions/dataset.go
Labels: in progress

#420 feat(backtrace): Show error's stack if QRI_BACKTRACE is defined
  cmd/cmd.go
Labels: in progress

#421 fix(ipfs): Display better error if IPFS is holding a lock
  cmd/repo.go
Labels: in progress

#423 fix(list): Show info for datasets even if they don't have meta
  cmd/print.go
Labels: in progress
