Repository qri-io/qri, pull requests merged in 2018-04, with the labels that each got.

#330 fix(config): fix issues created by config overhaul
  api/server.go
  cmd/config.go
  cmd/connect.go
  cmd/repo.go
  cmd/setup.go
  config/api.go
  config/config.go
  config/config_test.go
  config/profile.go
  config/profile_test.go
  config/rpc.go
  config/webapp.go
  repo/profile/type.go
Labels: fix, in progress

#331 Dockerfile: Use unambiguous adduser arguments
  Dockerfile
Labels: fix

#339 refactor(connect flags): add disable flags for api, rpc, and port
  api/transports.go
  cmd/connect.go
Labels: in progress

#340 chore(deps): bump IPFS to version 0.4.14
  api/peers.go
  config/p2p.go
  config/webapp.go
  core/peers.go
  core/self_update.go
  core/self_update_test.go
  p2p/bootstrap.go
  p2p/config.go
  p2p/datasets.go
  p2p/discovery.go
  p2p/events.go
  p2p/message.go
  p2p/node.go
  p2p/node_test.go
  p2p/p2p.go
  p2p/p2p_test.go
  p2p/peers.go
  p2p/ping.go
  p2p/profile.go
  p2p/profile_test.go
  p2p/profiles.go
  p2p/wrapped_stream.go
  package.json
  repo/fs/profile_store.go
  repo/profile/id.go
  repo/profile/profile.go
  repo/profile/store.go
Labels: in progress

#341 refactor(repo): remove references to Abstract dataset structs
  repo/graph.go
Labels: in progress

#343 refactor(fsrepo): remove profile.json storage, fix peerstore invalid marshaling.
  api/server.go
  api/server_test.go
  cmd/add.go
  cmd/cmd_test.go
  cmd/config.go
  cmd/connect.go
  cmd/repo.go
  cmd/setup.go
  config/api.go
  config/logging.go
  config/p2p.go
  p2p/bootstrap.go
  p2p/discovery.go
  p2p/node.go
  p2p/p2p.go
  p2p/peers.go
  repo/fs/files.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/fs/profile_store.go
  repo/profile/id.go
Labels: in progress

#345 feat(cmd.Config): added qri config export command
  cmd/config.go
  cmd/print.go
  cmd/setup.go
  config/profile.go
Labels: feat, fix, in progress

#346 fix(webapp): hide webapp hash behind vanity url
  api/root.go
  api/server.go
  api/templates.go
  api/webapp.go
  cmd/repo.go
  config/webapp.go
  repo/fs/fs.go
Labels: in progress

#348 refactor(config): move global config into core, refactor CLI config loading
  cmd/add.go
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/config.go
  cmd/connect.go
  cmd/connections.go
  cmd/data.go
  cmd/diff.go
  cmd/export.go
  cmd/info.go
  cmd/list.go
  cmd/log.go
  cmd/logging.go
  cmd/peer.go
  cmd/peers.go
  cmd/print.go
  cmd/profile.go
  cmd/remove.go
  cmd/rename.go
  cmd/repo.go
  cmd/root.go
  cmd/save.go
  cmd/search.go
  cmd/setup.go
  cmd/validate.go
  cmd/version.go
  core/config.go
  main.go
  repo/fs/files.go
  repo/fs/fs.go
Labels: in progress

#344 feat(config): validation and documentation
  api/server.go
  cmd/setup.go
  config/api.go
  config/api_test.go
  config/cli.go
  config/cli_test.go
  config/config.go
  config/config_test.go
  config/logging.go
  config/logging_test.go
  config/p2p.go
  config/p2p_test.go
  config/profile.go
  config/profile_test.go
  config/readme.md
  config/repo.go
  config/repo_test.go
  config/rpc.go
  config/rpc_test.go
  config/store.go
  config/store_test.go
  config/webapp.go
  config/webapp_test.go
  p2p/node.go
  repo/fs/fs_test.go
Labels: in progress

#349 chore(release): release 0.3.0
  CHANGELOG.md
  api/server.go
  api/server_test.go
  api/testdata/profileResponse.json
  api/transports.go
  api/webapp.go
  cmd/cmd_test.go
  cmd/config.go
  cmd/connect.go
  cmd/info.go
  cmd/profile.go
  cmd/repo.go
  cmd/root.go
  cmd/setup.go
  cmd/version.go
  config/api.go
  config/config.go
  config/config_test.go
  config/rpc.go
  config/testdata/default.yaml
  config/webapp.go
  core/config.go
  core/config_test.go
  core/profile.go
  core/profile_test.go
  repo/fs/fs.go
  repo/test/test_repo.go
Labels: in progress

#350 fix(connect): fix errors caused by running connect with setup
  api/server.go
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/connect.go
  cmd/connect_test.go
  cmd/root.go
  cmd/setup.go
  cmd/version.go
  config/api.go
Labels: in progress

#353 fix(webapp): replaced hardcoded entryupintupdateaddress
  api/webapp.go
Labels: in progress

#356 fix(config): `qri config set` on an int field does not actually update
  cmd/cmd_test.go
  config/config.go
Labels: in progress

#360 refactor(api): make api root a status check
  api/root.go
  api/server_test.go
Labels: in progress

#358 docs(config): expand config readme.md
  config/readme.md
Labels: in progress

#363 refactor: photo endpoints, mutex fixes, makefile updates
  .circleci/config.yml
  DEVELOPERS.md
  Makefile
  api/profile.go
  api/server.go
  api/testdata/profileResponse.json
  cmd/cmd_test.go
  config/profile.go
  config/profile_test.go
  core/core_test.go
  core/profile.go
  core/profile_test.go
  p2p/node.go
  p2p/node_test.go
  p2p/profile.go
  repo/actions/dataset_test.go
  repo/fs/fs.go
  repo/fs/profile_store.go
  repo/profile/profile.go
  repo/profile/store.go
  repo/ref_test.go
  repo/test/test_repo.go
Labels: fix, in progress, refactor

#362 feat(registry): Integrate Registries into codebase
  Makefile
  cmd/cmd_test.go
  cmd/connect.go
  cmd/connect_test.go
  cmd/setup.go
  core/setup.go
Labels: feat, fix, in progress

#364 fix(core.StructuredData): top level object support for Data commands, core.Diff fixes
  api/datasets.go
  api/peers.go
  api/root.go
  api/testdata/listResponse.json
  cmd/cmd.go
  cmd/connections.go
  cmd/diff.go
  cmd/info.go
  cmd/peer.go
  cmd/peers.go
  cmd/print.go
  config/config.go
  config/config_test.go
  core/datasets.go
  core/datasets_test.go
  core/peers.go
  core/peers_test.go
  core/setup.go
  core/setup_test.go
  p2p/node.go
  p2p/peers.go
  repo/fs/profile_store.go
  repo/profile/id.go
  repo/test/test_repo.go
  repo/test/test_repo_test.go
  repo/test/testdata/sitemap/data.json
  repo/test/testdata/sitemap/input.dataset.json
Labels: fix, in progress, refactor

#366 feat(cli): organize commands into groups
  api/peers.go
  api/profile.go
  api/root.go
  api/server_test.go
  api/testdata/profileRequest.json
  api/testdata/profileResponse.json
  cmd/add.go
  cmd/config.go
  cmd/connect.go
  cmd/connections.go
  cmd/data.go
  cmd/diff.go
  cmd/export.go
  cmd/info.go
  cmd/list.go
  cmd/log.go
  cmd/peer.go
  cmd/peers.go
  cmd/print.go
  cmd/remove.go
  cmd/rename.go
  cmd/repo.go
  cmd/root.go
  cmd/save.go
  cmd/search.go
  cmd/setup.go
  cmd/templates.go
  cmd/validate.go
  cmd/version.go
  config/profile.go
  config/profile_test.go
  core/datasets.go
  core/peers.go
  core/peers_test.go
  core/profile.go
  core/profile_test.go
  core/schemas/profileSchema.json
  core/setup.go
  p2p/profile.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/fs/profile_store.go
  repo/profile/profile.go
  repo/profile/profile_test.go
  repo/test/test_repo.go
Labels: in progress

#369 chore(makefile): escape dollar sign so error displays correctly
  Makefile
Labels: in progress

#370 fix(core.Add): major cleanup to make add work, bail on commands that currently don't work over RPC
  api/datasets.go
  api/testdata/addResponseFromURL.json
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/removeResponseByPath.json
  api/testdata/removeResponseWithPath.json
  api/testdata/renameResponse.json
  api/testdata/saveMetaResponse.json
  cmd/add.go
  cmd/cmd.go
  cmd/data.go
  cmd/diff.go
  cmd/export.go
  cmd/log.go
  cmd/print.go
  cmd/repo.go
  cmd/save.go
  cmd/validate.go
  core/datasets.go
  core/datasets_test.go
  core/profile.go
  p2p/dataset.go
  p2p/peers.go
  p2p/profile.go
  repo/actions/dataset.go
  repo/fs/fs.go
  repo/graph.go
  repo/ref.go
Labels: fix, in progress

#371 chore(release): release v0.3.1
  CHANGELOG.md
  cmd/version.go
  config/webapp.go
Labels: chore, in progress
