Repository qri-io/qri, pull requests merged in 2018-07, with the labels that each got.

#476 feat: Pin on publish
  api/testdata/statusResponse.json
  cmd/cmd_test.go
  cmd/connect.go
  cmd/qri.go
  cmd/registry.go
  cmd/remove_test.go
  cmd/rename_test.go
  cmd/render_test.go
  cmd/save.go
  cmd/save_test.go
  cmd/search_test.go
  cmd/test_factory.go
  cmd/use_test.go
  cmd/validate_test.go
  lib/datasets.go
  lib/datasets_test.go
  lib/registry.go
  lib/search.go
  repo/actions/registry.go
  repo/repo.go
Labels: feat, in progress

#475 feat(api/registry, api/search, api/version): add api endpoints to get closer to command line functionality
  api/datasets.go
  api/registry.go
  api/root.go
  api/search.go
  api/server.go
  api/server_test.go
  api/testdata/addResponseFromFile.json
  api/testdata/addResponsePrivate.json
  api/testdata/cities/init_dataset.json
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  api/testdata/historyResponse.json
  api/testdata/historyResponseAt.json
  api/testdata/historyResponsePath.json
  api/testdata/listResponse.json
  api/testdata/photoResponse.json
  api/testdata/posterResponse.json
  api/testdata/profileResponseInitial.json
  api/testdata/publishResponse.json
  api/testdata/removeResponse.json
  api/testdata/removeResponseWithPath.json
  api/testdata/saveMetaResponse.json
  api/testdata/searchRequest.json
  api/testdata/searchResponse.json
  api/testdata/statusResponse.json
  api/testdata/unpublishResponse.json
  cmd/version.go
  lib/lib.go
  lib/registry.go
  lib/search.go
  repo/actions/registry.go
Labels: in progress

#478 fix(add): Work-around for RPC error that breaks `qri add`.
  api/server_test.go
  lib/datasets.go
Labels: in progress

#483 feat(viz): add viz api endpoint, viz refactor
  api/datasets.go
  api/registry.go
  api/render.go
  api/server.go
  api/server_test.go
  api/testdata/addRequestFromURL.json
  api/testdata/addResponseFromURL.json
  api/testdata/getResponseFamilyRelationships.json
  api/testdata/removeResponseByPath.json
  api/testdata/statusResponse.json
  cmd/add.go
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/registry.go
  lib/datasets.go
  lib/lib.go
  lib/render.go
  repo/actions/dataset.go
  repo/actions/transform.go
  repo/actions/viz.go
Labels: feat, in progress

#484 chore(release): release v0.5.1-rc1
  CHANGELOG.md
  api/testdata/statusResponse.json
  config/p2p.go
  config/testdata/default.yaml
  config/webapp.go
  lib/lib.go
Labels: in progress

#488 fix(peers): If user is not connected, show error instead of segfaulting.
  lib/peers.go
  lib/peers_test.go
Labels: in progress

#490 chore(cmd): Rename DataOptions to BodyOptions, other small fixes
  cmd/body.go
  cmd/cmd.go
  repo/actions/transform.go
Labels: in progress

#489 fix(rpc): Register types with gob to avoid "reading body EOF" errors
  api/server_test.go
  lib/datasets.go
  lib/lib.go
Labels: in progress

#493 refactor(render): replace template lookup with hardcoded template
  cmd/get.go
  cmd/get_test.go
  cmd/render_test.go
  config/p2p.go
  lib/render.go
  lib/render_test.go
Labels: fix, in progress, refactor

#495 refactor(cmd/export): `--blank` flag returns dataset.yaml with `viz` instructions
  cmd/export.go
Labels: in progress

#496 chore(release): release 0.5.1
  CHANGELOG.md
  api/testdata/statusResponse.json
  config/webapp.go
  lib/lib.go
Labels: chore, in progress

#499 test(cmd/factory): added a test for EnvPathFactory
  cmd/factory_test.go
Labels: test

#500 fix(profile): Using config set profile.something calls SaveProfile.
  cmd/config.go
  config/config.go
  config/profile.go
  config/profile_test.go
Labels: in progress

#501 feat(profile): Detect peername renames when listing datasets.
  lib/datasets.go
  lib/profile.go
  repo/ref.go
  repo/ref_test.go
Labels: in progress

#504 test(repo/events): Added tests for MemEventLog
  repo/events_test.go
Labels: test
