Repository qri-io/qri, pull requests merged in 2018-10, with the labels that each got.

#554 feat(ConvertBodyFile): new action to convert body data
  actions/body.go
  actions/dataset.go
  actions/transform.go
  api/datasets.go
Labels: feat, fix, in progress

#555 chore(release): release v.0.5.4
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: chore, in progress

#557 docs(README): updating readme, modeled after cyclejs readme
  README.md
Labels: in progress

#556 refactor(crypto): Extract key generation into repo/gen. Speeds up tests.
  cmd/cmd.go
  cmd/cmd_test.go
  cmd/connect_test.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/generate/generate.go
  cmd/qri.go
  cmd/setup.go
  config/config.go
  config/p2p.go
  config/profile.go
  config/profile_test.go
  docs/docs.go
  lib/config_test.go
  lib/setup_test.go
  repo/fs/fs_test.go
  repo/gen/crypto_generator.go
Labels: in progress

#558 docs(readme): edit packages names
  README.md
Labels: in progress

#560 docs(readme): adjust building from source docs based on issue #485
  README.md
Labels: in progress

#562 feat(RequestDatasetLog): add back functionality for getting a peer's …
  p2p/log.go
  p2p/log_test.go
  p2p/node.go
  p2p/peers.go
  p2p/testdata/brandyn/counter/body.csv
  p2p/testdata/cassie/flourinated_compounds_in_fast_food_packaging/body.cbor
  p2p/testdata/omar/movies/body.csv
  p2p/testdata/ricky/cities/body.csv
  p2p/testdata/tim/craigslist/body.json
Labels: in progress

#563 chore(release): release v0.5.5
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: in progress

#564 test(ipfs): Mock out IPFS repo creation, final change to speed up tests
  actions/setup.go
  actions/setup_test.go
  cmd/cmd_test.go
  cmd/connect_test.go
  cmd/factory_test.go
  cmd/setup.go
  lib/setup.go
  lib/setup_test.go
  lib/test/test_crypto_generator.go
  lib/test/testdata/empty_ipfs_repo.zip
  p2p/log.go
  repo/gen/crypto_generator.go
Labels: in progress

#568 fix(export): Blank yaml file should have correct fields
  api/testdata/api.snapshot
  cmd/export.go
  lib/lib.go
  p2p/p2p.go
Labels: in progress

#569 fix(new): Take absolute path to body file before loading it in `new`.
  cmd/new.go
Labels: in progress

#572 feat(export): Always export by zip for now, until full RFC is implemented
  api/datasets.go
  api/testdata/api.snapshot
  cmd/export.go
Labels: in progress

#574 Unpack endpoint gets a zip and sends back its contents
  api/api.go
  api/api_test.go
  api/dataset_test.go
  api/datasets.go
  api/testdata/api.snapshot
  api/testdata/exported.zip
Labels: in progress

#571 fix(p2p.RequestProfile, p2p.handleProfile): receiving peer does not save profile to repo
  p2p/connected.go
  p2p/dataset_test.go
  p2p/datasets_test.go
  p2p/events_test.go
  p2p/log_test.go
  p2p/node.go
  p2p/peers.go
  p2p/ping_test.go
  p2p/profile.go
  p2p/profile_test.go
  p2p/qri_peers_test.go
Labels: in progress

#576 chore(release): release v0.5.6
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: chore, in progress

#583 feat(starlark): renamed, reworked starlark syntax & transforms
  .circleci/config.yml
  Makefile
  README.md
  actions/transform.go
  actions/transform_test.go
  api/datasets.go
  cmd/export.go
  cmd/search_test.go
  lib/datasets_test.go
  lib/search_test.go
  lib/testdata/tf/transform.sky
  lib/testdata/tf/transform.star
Labels: in progress

#582 refactor(p2p): p2p and p2ptest need a refactor to clarify and slim down what we do to connect with a peer
  api/api.go
  p2p/bootstrap.go
  p2p/connected.go
  p2p/discovery.go
  p2p/node.go
  p2p/node_test.go
  p2p/peers.go
  p2p/peers_test.go
  p2p/profile_test.go
  p2p/test/p2ptest.go
  p2p/test/p2ptest_test.go
  p2p/test/testable_node_test.go
  p2p/test/testdata/brandyn/config.yaml
  p2p/test/testdata/brandyn/counter/body.csv
  p2p/test/testdata/brandyn/counter/input.dataset.json
  p2p/test/testdata/cassie/config.yaml
  p2p/test/testdata/cassie/flourinated_compounds_in_fast_food_packaging/body.cbor
  p2p/test/testdata/cassie/flourinated_compounds_in_fast_food_packaging/input.dataset.json
  p2p/test/testdata/omar/config.yaml
  p2p/test/testdata/omar/movies/body.csv
  p2p/test/testdata/omar/movies/input.dataset.json
  p2p/test/testdata/ricky/cities/body.csv
  p2p/test/testdata/ricky/cities/input.dataset.json
  p2p/test/testdata/ricky/config.yaml
Labels: in progress

#581 feat(save): Merge command `new` into `save`.
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  actions/registry_test.go
  actions/select_test.go
  api/api.go
  api/api_test.go
  api/dataset_test.go
  api/datasets.go
  api/testdata/api.snapshot
  cmd/cmd_test.go
  cmd/new.go
  cmd/qri.go
  cmd/save.go
  cmd/save_test.go
  config/webapp.go
  lib/datasets.go
  lib/datasets_test.go
Labels: in progress

#584 feat(DatasetRef.Published): add "published" flag to dataset ref, support for storing published in fsrepo
  .circleci/config.yml
  repo/fs/fs_test.go
  repo/fs/refstore.go
  repo/graph_test.go
  repo/mem_refstore.go
  repo/ref.go
  repo/ref_test.go
  repo/test/test.go
  repo/test/test_profilestore.go
  repo/test/test_refstore.go
  repo/test/test_repo.go
  repo/test/test_repo_test.go
Labels: feat, in progress, test

#586 feat(base): defining base package
  actions/dataset.go
  actions/dataset_head.go
  actions/dataset_test.go
  actions/list_datasets.go
  actions/log.go
  actions/render_test.go
  actions/select_test.go
  base/base.go
  base/base_test.go
  base/dataset.go
  base/dataset_test.go
  base/datasets.go
  base/datasets_test.go
  base/log.go
  base/log_test.go
  base/render.go
  base/render_test.go
  base/select.go
  base/select_test.go
  base/testdata/bad.yaml
  base/testdata/oh_hai.yaml
  base/testdata/schools.cbor
  base/viz.go
  base/viz_test.go
  cmd/get.go
  cmd/render_test.go
  lib/render.go
  lib/render_test.go
  p2p/datasets.go
  p2p/log_test.go
  repo/dataset_test.go
  repo/fs/fs.go
  repo/repo_test.go
  repo/test/test_repo.go
Labels: in progress, refactor

#585 Refactor(AddQriPeer): rename `AddQriPeer` to `UpgradeToQriConnection` and formalize it's role
  actions/dataset_ref_test.go
  actions/dataset_test.go
  actions/peers_test.go
  lib/datasets_test.go
  p2p/bootstrap.go
  p2p/connected_test.go
  p2p/dataset_test.go
  p2p/datasets_test.go
  p2p/discovery.go
  p2p/events_test.go
  p2p/log_test.go
  p2p/network_notifee.go
  p2p/node.go
  p2p/p2p.go
  p2p/peers.go
  p2p/peers_test.go
  p2p/ping_test.go
  p2p/profile_test.go
  p2p/qri_peers.go
  p2p/qri_peers_test.go
  p2p/resolve_ref_test.go
  p2p/test/p2ptest.go
  p2p/test/p2ptest_test.go
  p2p/test/testable_node_test.go
Labels: in progress

#590 feat(Publish): add publish command, basic API endpoints
  actions/dataset.go
  actions/list_datasets.go
  actions/list_datasets_test.go
  api/api.go
  api/dataset_test.go
  api/datasets.go
  api/testdata/api.snapshot
  base/dataset.go
  base/dataset_test.go
  base/datasets.go
  base/datasets_test.go
  base/ref.go
  base/ref_test.go
  cmd/cmd_test.go
  cmd/list.go
  cmd/publish.go
  cmd/publish_test.go
  cmd/qri.go
  cmd/registry.go
  cmd/save.go
  lib/datasets.go
  lib/lib.go
  lib/params.go
  p2p/datasets.go
  repo/fs/refstore.go
  repo/mem_refstore.go
  repo/ref.go
  repo/test/test_refstore.go
Labels: feat, in progress

#592 refactor(save): large refactoring for saving datasets
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  actions/merge_events_test.go
  actions/registry_test.go
  actions/transform.go
  api/testdata/api.snapshot
  base/base_test.go
  base/dataset.go
  base/dataset_prepare.go
  base/dataset_prepare_test.go
  base/dataset_test.go
  base/dataset_update.go
  base/viz.go
  base/viz_test.go
  lib/datasets.go
  p2p/log_test.go
  repo/profile/store.go
  repo/test/test_repo.go
Labels: in progress

#593 fix(bootstrap peers): fix network not ever contacting bootstrap peers
  p2p/discovery.go
Labels: fix, in progress
