Repository qri-io/qri, pull requests merged in 2018-11, with the labels that each got.

#597 fix(qri): Fix usage of dataset and startf
  actions/transform.go
  base/dataset.go
Labels: in progress

#595 feat(Update): add update command & API endpoint
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  actions/log.go
  actions/testdata/now_tf/input.dataset.json
  actions/testdata/now_tf/transform.star
  actions/transform.go
  actions/transform_test.go
  api/api.go
  api/dataset_test.go
  api/datasets.go
  api/testdata/api.snapshot
  base/base_test.go
  base/dataset.go
  base/dataset_test.go
  base/dataset_update.go
  base/log.go
  base/log_test.go
  base/viz.go
  cmd/qri.go
  cmd/update.go
  cmd/update_test.go
  lib/datasets.go
  p2p/log_diff.go
  p2p/log_diff_test.go
  p2p/node.go
Labels: feat, in progress

#599 feat(save): add support for saving from zip archives
  actions/dataset.go
  api/datasets.go
  api/testdata/api.snapshot
  base/dataset.go
  base/dataset_prepare.go
  base/dataset_test.go
  cmd/save.go
  cmd/save_test.go
  lib/datasets.go
  lib/datasets_test.go
  lib/file.go
  lib/file_test.go
  lib/testdata/import.zip
  repo/ref.go
Labels: feat, in progress

#598 fix(fs Profile Store): fix lock pass-by-value error
  cmd/factory.go
  lib/search.go
  repo/fs/fs.go
  repo/fs/profile_store.go
Labels: fix, in progress

#602 refactor(api.saveHandler, lib.Save, base.CreateDataset): add ability to use DryRun and ReturnBody flags
  actions/dataset.go
  actions/transform.go
  actions/transform_test.go
  api/datasets.go
  base/dataset.go
  lib/datasets.go
  lib/file.go
Labels: in progress

#600 refactor: Distinguish Manual & Scripted Tranforms
  actions/dataset.go
  actions/transform.go
  actions/transform_test.go
  lib/file.go
Labels: in progress, refactor

#603 refactor: Mutually Exclusive Manual & Scripted Tranforms
  Makefile
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  actions/diff_test.go
  actions/recall.go
  actions/recall_test.go
  actions/transform.go
  base/dataset.go
  base/dataset_prepare.go
  base/dataset_prepare_test.go
  base/dataset_test.go
  base/revisions.go
  base/revisions_test.go
  cmd/save.go
  cmd/save_test.go
  cmd/update.go
  lib/datasets.go
  lib/datasets_test.go
  lib/file.go
  lib/lib_test.go
  lib/peers_test.go
  lib/testdata/now_tf/input.dataset.json
  lib/testdata/now_tf/transform.star
  rev/rev.go
  rev/rev_test.go
Labels: feat, in progress, refactor

#604 fix(fs refstore): don't store DatasetPod in refstore
  repo/fs/refstore.go
Labels: fix, in progress

#605 chore(release): release v0.6.0
  CHANGELOG.md
  Makefile
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: chore, in progress

#606 docs(changelog): fix broken changelog formatting
  CHANGELOG.md
Labels: docs, in progress

#608 fix(transform): Fix how secrets and config are passed into transform.
  actions/dataset.go
  actions/dataset_test.go
  actions/transform.go
  actions/transform_test.go
  api/testdata/api.snapshot
  lib/lib.go
Labels: fix, in progress

#610 fix(save): move secret passing out-of-band, fix updates to viz
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  actions/registry_test.go
  api/datasets.go
  base/dataset.go
  base/dataset_prepare.go
  base/viz.go
  base/viz_test.go
  cmd/print.go
  cmd/save.go
  cmd/update.go
  lib/datasets.go
  lib/lib_test.go
  p2p/p2p.go
Labels: fix, in progress

#611 feat(ipfs): update go-ipfs dependency to version 0.4.18
  actions/actions_test.go
  actions/dataset.go
  actions/merge_events_test.go
  actions/peers.go
  actions/registry.go
  actions/registry_test.go
  actions/setup.go
  api/datasets.go
  cmd/print.go
  cmd/publish.go
  cmd/qri.go
  cmd/registry.go
  cmd/save_test.go
  cmd/setup_test.go
  config/p2p.go
  config/test/test_peers.go
  lib/datasets.go
  lib/peers.go
  lib/peers_test.go
  lib/profile.go
  lib/profile_test.go
  lib/registry_test.go
  lib/self_update.go
  lib/self_update_test.go
  lib/setup_test.go
  p2p/bootstrap.go
  p2p/connected.go
  p2p/datasets.go
  p2p/discovery.go
  p2p/events.go
  p2p/message.go
  p2p/network_notifee.go
  p2p/node.go
  p2p/p2p.go
  p2p/peers.go
  p2p/ping.go
  p2p/profile.go
  p2p/profile_test.go
  p2p/qri_peers.go
  p2p/test/p2ptest.go
  p2p/test/testable_node_test.go
  p2p/wrapped_stream.go
  package.json
  repo/events.go
  repo/events_test.go
  repo/fs/profile_store.go
  repo/fs/profile_store_test.go
  repo/profile/id.go
  repo/profile/profile.go
  repo/profile/store.go
Labels: chore, in progress

#613 fix(format): Detect format change when saving, either error or rewrite
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  api/datasets.go
  base/dataset.go
  base/dataset_test.go
  cmd/save_test.go
  lib/datasets.go
  lib/lib_test.go
Labels: in progress

#617 feat(cmd registry pin): add registry pin commands
  actions/registry.go
  api/api_test.go
  base/ref.go
  cmd/cmd_test.go
  cmd/publish.go
  cmd/registry.go
  cmd/save_test.go
  lib/datasets.go
  lib/registry.go
Labels: feat, in progress

#620 feat(registry): create api endpoint to request list of available datasets from the registry
  actions/registry.go
  actions/registry_test.go
  api/api.go
  api/registry.go
  api/registry_test.go
  api/testdata/api.snapshot
  lib/registry.go
  lib/registry_test.go
  p2p/dataset.go
  p2p/log.go
  p2p/peers.go
  p2p/resolve_ref.go
Labels: in progress

#624 refactor(api): endpoint changed from `registry/list` to `registry/datasets`
  api/api.go
  api/registry.go
  api/registry_test.go
  api/testdata/api.snapshot
Labels: in progress

#625 fix(webapp): restore webapp
  api/api.go
  api/templates.go
  api/transports.go
  api/transports_test.go
  api/webapp.go
  api/webapp_test.go
Labels: fix, in progress

#627 test(save): Test case for saving a dataset with a relative body path.
  cmd/cmd_test.go
  cmd/testdata/movies/ds_ten.yaml
Labels: in progress

#628 refactor(registry): remove `status` and replace it with `registryDataset`
  actions/registry.go
  actions/registry_test.go
  api/api_test.go
  api/registry.go
  cmd/registry.go
  cmd/remove_test.go
  cmd/save_test.go
  lib/registry.go
  lib/registry_test.go
  repo/ref.go
Labels: in progress

#629 feat(online): Set Online flag for peers when using lib.Info. Cleanups.
  actions/peers.go
  actions/peers_test.go
  lib/peers.go
Labels: in progress
