Repository qri-io/qri, pull requests merged in 2018-12, with the labels that each got.

#631 docs(*): updating errors in docs
  .github/CONTRIBUTING.md
  CONTRIBUTOR.md
  DEVELOPERS.md
  cmd/add.go
  cmd/export.go
  cmd/list.go
  cmd/publish.go
  cmd/save.go
Labels: in progress

#634 feat(dag): use DAG manifests for faster, dependable registry integration
  Dockerfile
  Makefile
  actions/dataset.go
  actions/dataset_ref.go
  actions/manifest.go
  actions/registry.go
  api/api.go
  api/registry.go
  base/manifest.go
  cmd/manifest.go
  cmd/print.go
  cmd/publish.go
  cmd/qri.go
  cmd/registry.go
  cmd/search_test.go
  cmd/update_test.go
  config/p2p.go
  lib/datasets.go
  lib/datasets_test.go
  lib/log_test.go
  lib/registry.go
  lib/registry_test.go
  lib/render_test.go
  p2p/bootstrap.go
  package.json
  repo/ref.go
Labels: feat, in progress

#635 fix(publish): api publish endpoint and CanonicalizeDatasetRef fix
  actions/actions.go
  api/datasets.go
  repo/ref.go
Labels: in progress

#636 fix(config migration): add config migration to update p2p.QriBootstrapAddrs
  cmd/qri.go
  config/config.go
  config/config_test.go
  config/migrate/migrate.go
  config/p2p.go
  config/testdata/simple.yaml
  lib/config.go
  lib/config_test.go
Labels: fix, in progress

#637 refactor(config): Rename Config constructors.
  cmd/setup.go
  config/config.go
  config/migrate/migrate.go
  config/p2p.go
  config/profile.go
  config/test_config.go
  lib/peers_test.go
  p2p/test/p2ptest.go
Labels: in progress

#638 fix(cfg.Migration, ResolveDatasetRef): pre-release fixes
  actions/dataset_ref.go
  config/migrate/migrate.go
  p2p/resolve_ref.go
Labels: fix, in progress

#639 chore(release): release 0.6.1
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: chore, in progress

#641 fix(p2p dsinfo): repo.ErrNotFound when p2p can't find dataset info
  Makefile
  api/testdata/api.snapshot
  lib/lib.go
  p2p/dataset.go
  p2p/p2p.go
Labels: fix, in progress, network/p2p
