Repository qri-io/qri, pull requests merged in 2019-03, with the labels that each got.

#701 fix(get dataset): return a datasetRef, not a dataset!
  api/datasets.go
  api/root.go
  api/testdata/api.snapshot
Labels: in progress

#702 fix(actions.SaveDataset): delay inferring values until after writing changes
  Makefile
  actions/dataset.go
  cmd/cmd_test.go
  cmd/diff.go
  cmd/save_test.go
  lib/diff_test.go
Labels: dataset, fix, in progress

#703 chore(release): release v0.7.1
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: chore, in progress

#708 chore(release): release v0.7.2
  CHANGELOG.md
  Makefile
  actions/body.go
  actions/body_test.go
  actions/dataset.go
  actions/registry.go
  api/datasets.go
  api/testdata/api.snapshot
  base/dataset.go
  cmd/body.go
  cmd/body_test.go
  cmd/cmd.go
  cmd/get.go
  cmd/qri.go
  cmd/save.go
  cmd/save_test.go
  config/migrate/migrate.go
  lib/datasets.go
  lib/file.go
  lib/file_test.go
  lib/lib.go
  lib/testdata/viz/visualization.html
  p2p/p2p.go
Labels: CLI, chore, feat, fix, in progress

#706 fix(save): Better error message when saving with wrong file
  lib/file.go
Labels: in progress

#704 feat(remote): Beginning of "remote" mode implementation
  api/api.go
  api/datasets.go
  api/remote.go
  api/remote_test.go
  api/testdata/api.snapshot
  api/testdata/postRemoteRequest.json
  base/ref.go
  cmd/connect.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/publish.go
  cmd/qri.go
  config/api.go
  lib/datasets.go
  lib/params.go
  lib/remote.go
  lib/remote_test.go
Labels: in progress

#707 feat(remote): Parse config using FillStruct. Remotes field.
  api/testdata/api.snapshot
  base/fill_struct.go
  base/fill_struct_test.go
  config/config.go
  config/config_test.go
  config/remotes.go
  config/testdata/simple.yaml
  lib/config.go
  lib/lib.go
  p2p/p2p.go
Labels: in progress

#710 fix(fill_struct): Work with non-pointer structs and pointers to non-structs
  api/remote.go
  base/fill_struct.go
  base/fill_struct_test.go
Labels: in progress

#705 feat(daginfo): add `qri daginfo` command that returns a dag.Info of a dataset
  Makefile
  actions/dag.go
  base/dag.go
  base/manifest.go
  cmd/dag.go
  cmd/dag_test.go
  cmd/get.go
  cmd/manifest.go
  cmd/qri.go
  lib/datasets.go
Labels: in progress

#711 fix(get): If format is mispelled, display an error
  lib/datasets.go
  lib/datasets_test.go
Labels: in progress

#712 refactor(fill): Move base/FillStruct to base/fill/Struct
  base/fill/struct.go
  base/fill/struct_test.go
  config/config.go
  config/config_test.go
  config/testdata/default.yaml
  lib/config.go
  lib/file.go
Labels: in progress

#715 fix(tests): Save with viz needs html format, update testdata file
  cmd/save_test.go
  cmd/testdata/movies/dataset_with_viz.json
Labels: in progress

#714 feat(remotes): base/fill/PathValue used by Config, to enable Remotes
  base/fill/path_value.go
  base/fill/path_value_test.go
  cmd/config.go
  config/config.go
  config/config_test.go
  config/remotes.go
  lib/datasets_test.go
  lib/remote.go
Labels: in progress

#718 feat(save): Save a dataset with multiple file arguments
  cmd/cmd_test.go
  cmd/save.go
  cmd/save_test.go
  cmd/testdata/movies/structure_override.json
  lib/datasets.go
  lib/datasets_test.go
  lib/file.go
  lib/file_test.go
Labels: in progress

#721 fix(api): Listen on localhost for API and RPC
  api/api.go
  api/transports.go
  config/api.go
Labels: in progress
