Repository qri-io/qri, pull requests merged in 2019-01, with the labels that each got.

#647 feat(api): always include script output in POST /dataset responses
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  actions/registry_test.go
  actions/transform.go
  actions/transform_test.go
  api/datasets.go
  api/testdata/api.snapshot
  cmd/remove_test.go
  cmd/save_test.go
  lib/datasets.go
  lib/lib_test.go
  lib/registry_test.go
Labels: API, feat, in progress

#649 fix(Save): add tests to cmd that test you can save a transform and viz
  base/viz.go
  cmd/save_test.go
  cmd/testdata/movies/dataset_with_tf.json
  cmd/testdata/movies/dataset_with_viz.json
  cmd/testdata/movies/tf.star
  cmd/testdata/movies/viz.html
Labels: in progress

#650 fix(cmd): Both body and setup runnable during "qri connect"
  cmd/body.go
  cmd/cmd_test.go
  cmd/export.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/qri.go
  cmd/setup.go
  lib/datasets.go
Labels: in progress

#651 Update troubleshooting.md
  troubleshooting.md
Labels: docs

#656 fix(export): Check for unsupported export flags, recognize --format
  api/datasets.go
  api/testdata/api.snapshot
  cmd/cmd_test.go
  cmd/export.go
Labels: in progress

#663 fix(list): Listing a non-existant profile should not crash
  actions/list_datasets.go
  actions/list_datasets_test.go
Labels: in progress

#662 fix(remove): Remove requires the --revisions to specify what to delete
  actions/dataset.go
  actions/dataset_test.go
  api/datasets.go
  cmd/cmd_test.go
  cmd/remove.go
  cmd/remove_test.go
  cmd/testdata/movies/body_thirty.csv
  lib/datasets.go
  lib/datasets_test.go
  lib/params.go
  rev/rev.go
  rev/rev_test.go
Labels: in progress

#666 fix(print): Use int64 in print in order to support Arm6 (Raspberry Pi).
  cmd/print.go
Labels: in progress

#667 fix(export): Export can be used while running `qri connect`
  cmd/connect.go
  cmd/export.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/qri.go
  cmd/render_test.go
  lib/export.go
  lib/lib.go
  lib/lib_test.go
  lib/params.go
Labels: in progress

#670 docs: update package definition documentation
  base/base.go
  cmd/generate/generate.go
  config/test/test_peers.go
  docs/docs.go
  lib/test/test_crypto_generator.go
  main.go
  p2p/test/p2ptest.go
  repo/fs/fs.go
  repo/profile/profile.go
  repo/search/search.go
Labels: docs, in progress

#672 feat: Ipfs api
  cmd/export.go
  cmd/qri.go
  config/store.go
Labels: config, feat, in progress, network

#673 chore(release): release v0.6.2
  CHANGELOG.md
  api/testdata/api.snapshot
  cmd/save_test.go
  lib/lib.go
Labels: chore, in progress

#674 fix(get): Datasets whose name contains a field should work with get
  cmd/get.go
  cmd/get_test.go
Labels: in progress

#675 chore(version): Bump version identifier to 0.6.3-dev
  api/testdata/api.snapshot
  lib/lib.go
Labels: in progress

#676 fix(save): Infer more values, such as Schema, when appropriate
  base/dataset_prepare.go
  base/dataset_prepare_test.go
Labels: in progress

#677 refactor: use string values instead of datastore.Key
  Makefile
  actions/body.go
  actions/dataset.go
  actions/registry.go
  api/api.go
  api/testdata/api.snapshot
  base/dataset.go
  base/dataset_prepare.go
  base/log.go
  base/render.go
  base/revisions.go
  base/revisions_test.go
  base/select.go
  base/viz.go
  base/viz_test.go
  cmd/cmd_test.go
  cmd/render_test.go
  lib/datasets_test.go
  lib/profile.go
  lib/profile_test.go
  p2p/dataset.go
  p2p/log.go
  repo/fs/files.go
  repo/fs/profile_store.go
  repo/fs/refstore.go
  repo/graph.go
  repo/graph_test.go
  repo/profile/profile.go
  repo/profile/profile_test.go
  repo/repo.go
  repo/search/index.go
  repo/test/test_refstore.go
Labels: in progress, refactor

#680 fix(get): Turn `body` into a selector of the `get` command
  actions/body.go
  actions/body_test.go
  api/datasets.go
  api/root.go
  api/testdata/api.snapshot
  cmd/body.go
  cmd/cmd_test.go
  cmd/get.go
  cmd/get_test.go
  cmd/info.go
  lib/datasets.go
  lib/datasets_test.go
Labels: in progress
