Repository qri-io/qri, pull requests merged in 2019-06, with the labels that each got.

#786 chore: deprecate gx, switch to gomodules
  .circleci/config.yml
  .circleci/cover.test.sh
  Makefile
  README.md
  actions/dag.go
  actions/merge_events_test.go
  actions/remote.go
  api/api.go
  base/dag.go
  cmd/cmd_test.go
  cmd/list.go
  config/p2p.go
  config/test/test_peers.go
  go.mod
  go.sum
  lib/lib.go
  lib/lib_test.go
  lib/peers.go
  lib/self_update.go
  lib/self_update_test.go
  p2p/bootstrap.go
  p2p/connected.go
  p2p/datasets.go
  p2p/discovery.go
  p2p/events.go
  p2p/message.go
  p2p/network_notifee.go
  p2p/node.go
  p2p/p2p.go
  p2p/peers.go
  p2p/ping.go
  p2p/profile.go
  p2p/profile_test.go
  p2p/qri_peers.go
  p2p/test/p2ptest.go
  p2p/test/testable_node_test.go
  p2p/wrapped_stream.go
  package.json
  repo/events.go
  repo/events_test.go
  repo/fs/profile_store.go
  repo/fs/profile_store_test.go
  repo/profile/id.go
  repo/profile/profile.go
  repo/profile/store.go
  startf/context/context_test.go
  startf/ds/dataset_test.go
  startf/qri/qri.go
  startf/qri/qri_test.go
  startf/transform_test.go
Labels: chore

#787 fix: update cleanup with better CLI output
  api/webapp.go
  cmd/cmd_test.go
  cmd/stringers.go
  cmd/stringers_test.go
  cmd/update.go
  cmd/update_test.go
  lib/datasets.go
  lib/update.go
Labels: chore, fix, update

#788 feat(cron): add incrementing job number, refactor job names
  cmd/stringers.go
  cmd/stringers_test.go
  lib/update_test.go
  update/cron/cron.fbs
  update/cron/cron.go
  update/cron/cron_fbs/Job.go
  update/cron/cron_test.go
  update/cron/http_test.go
  update/cron/job.go
  update/cron/job_store_test.go
  update/cron/job_test.go
  update/cron/jobs.go
  update/update.go
Labels: feat

#789 chore(release): release v0.8.0
  CHANGELOG.md
  actions/diff.go
  api/testdata/api.snapshot
  go.mod
  go.sum
  lib/lib.go
  p2p/p2p.go
Labels: chore

#794 chore: make CI work again
  .circleci/config.yml
  api/testdata/api.snapshot
  go.sum
  lib/lib.go
  p2p/p2p.go
Labels: chore

#795 fix(setup): load plugins before attempting to setup IPFS
  go.sum
  lib/lib.go
  lib/lib_test.go
  lib/setup.go
Labels: fix, onboarding

#792 docs(viz): add outline comment for HTML viz templating
  base/render.go
Labels: docs

#799 chore(release): release v0.8.1
  CHANGELOG.md
  api/testdata/api.snapshot
  base/render.go
  cmd/cmd_test.go
  cmd/save_test.go
  go.mod
  go.sum
  lib/lib.go
  p2p/p2p.go
  startf/startf.go
Labels: chore, fix

#802 fix(add): add specific versions of a dataset using the full reference
  Makefile
  actions/dataset.go
  actions/dataset_ref.go
  actions/dataset_test.go
  api/testdata/api.snapshot
  base/dataset.go
  lib/lib.go
  p2p/p2p.go
Labels: chore, fix, refactor

#804 fix(webapp): must resolve path before passing path to frontend webapp handler
  api/webapp.go
  cmd/connect.go
  cmd/connect_test.go
  config/config.go
Labels: Breaking Change, CLI

#815 chore(release): Release v0.8.2
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
  p2p/p2p.go
Labels: chore, fix
