Repository qri-io/qri, pull requests merged in 2019-05, with the labels that each got.

#752 fix(pagination): add `page` and `pageSize` to api and `limit` and `offset` to cmd
  actions/peers.go
  actions/peers_test.go
  actions/registry.go
  api/datasets.go
  api/log.go
  api/search.go
  api/testdata/api.snapshot
  base/dataset.go
  base/log.go
  cmd/cmd_test.go
  cmd/get.go
  cmd/list.go
  cmd/log.go
  cmd/peers.go
  cmd/print.go
  cmd/search.go
  lib/datasets_test.go
  lib/log.go
  lib/log_test.go
  lib/peers.go
  lib/registry_test.go
  lib/search_test.go
  repo/test/test_repo.go
  repo/test/test_repo_test.go
Labels: in progress

#757 fix(p2p): pass missing context to ipfsfs.GoOnline
  p2p/node.go
Labels: fix, in progress

#759 fix(config): Check err when parsing config to avoid segfault
  lib/lib.go
Labels: in progress

#755 test(transform): Detect when transforms don't produce any changes
  cmd/cmd_test.go
  cmd/testdata/movies/tf_123.star
Labels: in progress

#758 fix(transform): Pass prev dataset to ExecScript
  actions/dataset.go
  actions/transform.go
  actions/transform_test.go
  cmd/cmd_test.go
  cmd/testdata/movies/body_two.json
  cmd/testdata/movies/tf_add_one.star
  lib/config.go
Labels: in progress

#760 feat(pager): to make it easier to read, long output on the cli is sent to a pager
  cmd/add.go
  cmd/diff.go
  cmd/diff_test.go
  cmd/get.go
  cmd/list.go
  cmd/log.go
  cmd/peers.go
  cmd/print.go
  cmd/print_test.go
  cmd/registry.go
  cmd/search.go
  cmd/search_test.go
  cmd/stringers.go
  cmd/stringers_test.go
  cmd/update.go
Labels: in progress

#767 refactor(api/body): add limit and offset params to api /body endpoint
  api/datasets.go
  api/datasets_test.go
  update/cron/job.go
Labels: in progress

#770 experimental support for multi-repo updates with --use-repo
  actions/dataset_test.go
  actions/testdata/now_tf/input.dataset.json
  cmd/stringers.go
  cmd/update.go
  lib/diff_test.go
  lib/testdata/now_tf/input.dataset.json
  lib/update.go
  update/cron/cron.fbs
  update/cron/cron_fbs/Job.go
  update/cron/job.go
  update/cron/job_test.go
  update/update.go
Labels: CLI, feat, in progress, update

#773 fix(config): fix api.Copy not copying all fields
  config/api.go
  config/api_test.go
Labels: fix

#774 fix(cmd): don't use FgWhite, breaks light-colored termimals
  cmd/diff.go
  cmd/print.go
Labels: CLI, fix

#776 fix(cmd): listing page 2 starts numbering at the offset
  cmd/list.go
  cmd/log.go
  cmd/peers.go
  cmd/print.go
  cmd/search.go
  cmd/update.go
Labels: CLI, fix

#784 refactor(apiutil): switch datatogether apiutil to qri-io/apiutil
  Makefile
  actions/remote_test.go
  api/api.go
  api/datasets.go
  api/log.go
  api/middleware.go
  api/peers.go
  api/profile.go
  api/registry.go
  api/remote.go
  api/render.go
  api/root.go
  api/search.go
  api/update.go
  cmd/get.go
  cmd/list.go
  cmd/log.go
  cmd/peers.go
  cmd/search.go
  cmd/update.go
  lib/params.go
  update/cron/http.go
Labels: API, refactor

#785 bring startf inline
  .gitignore
  Makefile
  README.md
  actions/transform.go
  go.mod
  startf/README.md
  startf/context/context.go
  startf/context/context_test.go
  startf/context/testdata/test.star
  startf/ds/dataset.go
  startf/ds/dataset_test.go
  startf/ds/doc.go
  startf/ds/entry_reader.go
  startf/ds/entry_reader_test.go
  startf/ds/entry_writer.go
  startf/ds/testdata/test.star
  startf/entry_reader.go
  startf/entry_reader_test.go
  startf/qri/entry_writer.go
  startf/qri/qri.go
  startf/qri/qri_test.go
  startf/qri/testdata/test.star
  startf/sandbox.go
  startf/startf.go
  startf/testdata/fetch.star
  startf/testdata/load_ds.star
  startf/testdata/meta_title.star
  startf/testdata/tf.star
  startf/transform.go
  startf/transform_test.go
Labels: chore, docs

#779 Cleanup update output
  Makefile
  cmd/dag.go
  cmd/print.go
  cmd/print_test.go
  cmd/search_test.go
  cmd/stringers.go
  cmd/stringers_test.go
  cmd/update.go
  update/update.go
Labels: CLI, feat, refactor
