Repository qri-io/qri, pull requests merged in 2019-11, with the labels that each got.

#999 fix(publish): Can only publish / unpublish a head reference
  cmd/publish.go
  lib/remote.go
Labels: fix, registry

#992 fix(diff): Diff implemented using Component interface
  api/testdata/api.snapshot
  base/component/component.go
  base/component/kinds.go
  cmd/diff.go
  cmd/fsi_integration_test.go
  cmd/ref_select.go
  cmd/ref_select_test.go
  go.mod
  go.sum
  lib/diff.go
  lib/diff_test.go
Labels: FSI, fix

#995 refactor(logbook): working identifers into logbook
  base/log.go
  base/ref.go
  cmd/cmd_test.go
  cmd/fetch_test.go
  cmd/fsi_integration_test.go
  cmd/log_test.go
  cmd/stringers.go
  fsi/init.go
  identity/identity.go
  identity/identity_test.go
  lib/datasets_test.go
  lib/log.go
  lib/log_test.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/http.go
  logbook/logsync/http_test.go
  logbook/logsync/logsync.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p.go
  logbook/logsync/p2p_test.go
  logbook/oplog/log.fbs
  logbook/oplog/log.go
  logbook/oplog/log_bench_test.go
  logbook/oplog/log_test.go
  logbook/oplog/logfb/Operation.go
  remote/remote.go
Labels: logbook, refactor

#1001 fix(remove): don't fail if remove encounters an issue traversing qfs history
  base/dataset.go
  go.mod
Labels: fix, lib

#1003 fix(log): Deleting a dataset ends the log for that dataset
  cmd/log_integration_test.go
  cmd/stringers.go
  lib/datasets.go
Labels: fix, logbook

#1004 fix(fsi): Init determines format from the --source-body-path flag
  cmd/init.go
Labels: FSI

#1005 chore(release): release v0.9.1
  CHANGELOG.md
  api/testdata/api.snapshot
  cmd/cmd_test.go
  cmd/save_test.go
  lib/lib.go
  startf/transform.go
Labels: chore

#1007 chore(actions): Remove references to the actions package
  README.md
  base/base.go
  fsi/body.go
  lib/datasets.go
  lib/export.go
  lib/lib_test.go
  lib/peers.go
Labels: chore

#1006 fix(windows): Set the .qri repo as hidden on Windows.
  base/set_file.go
  base/set_file_windows.go
  fsi/fsi.go
  lib/lib.go
Labels: fix, platform/windows

#1008 fix(ls): Don't crash when `list` runs over RPC
  lib/datasets.go
Labels: fix

#1009 feat: stats
  .gitignore
  api/api.go
  api/dataset_test.go
  api/datasets.go
  api/testdata/api.snapshot
  base/component/field_id.go
  base/dsfs/dataset.go
  cmd/get_test.go
  cmd/qri.go
  cmd/stats.go
  cmd/stats_test.go
  config/config.go
  config/stats.go
  config/stats_test.go
  config/testdata/default.yaml
  config/testdata/simple.yaml
  lib/datasets.go
  lib/datasets_test.go
  lib/lib.go
  lib/lib_test.go
  stats/cache.go
  stats/cache_test.go
  stats/stats.go
  stats/stats_test.go
Labels: feat

#1012 fix(remove): Fix multiple problems with remove
  api/datasets.go
  api/testdata/api.snapshot
  base/dataset.go
  base/dataset_test.go
  base/ref.go
  cmd/fsi_integration_test.go
  cmd/log_integration_test.go
  cmd/remove.go
  cmd/remove_integration_test.go
  cmd/remove_test.go
  fsi/fsi.go
  fsi/status.go
  lib/datasets.go
  lib/datasets_test.go
  remote/remote.go
Labels: FSI, fix

#1016 feat(readme): Can save readme component using --file flag
  base/dsdiff/.gitignore
  base/dsdiff/LICENSE
  base/dsdiff/README.md
  base/dsdiff/codecov.yml
  base/dsdiff/dsdiff.go
  base/dsdiff/dsdiff_test.go
  base/dsdiff/exp0.txt
  base/dsdiff/got0.txt
  base/dsdiff/test1.json
  base/dsdiff/testdata/newData.json
  base/dsdiff/testdata/newDescription.json
  base/dsdiff/testdata/newStructure.json
  base/dsdiff/testdata/newTitle.json
  base/dsdiff/testdata/newTransform.json
  base/dsdiff/testdata/newVisConfig.json
  base/dsdiff/testdata/orig.json
  base/dsdiff/testdata/structureJsonSchemaNew.json
  base/dsdiff/testdata/structureJsonSchemaOrig.json
  base/dsfs/dataset.go
  cmd/cmd_test.go
  cmd/fsi_integration_test.go
  cmd/log_integration_test.go
  cmd/remove_integration_test.go
  cmd/test_runner.go
  cmd/testdata/movies/about_movies.md
  go.mod
Labels: feat

#1018 fix(init): If init has errors, rollback changes
  base/component/component.go
  base/component/kinds.go
  cmd/fsi_integration_test.go
  cmd/log_integration_test.go
  fsi/fsi.go
  fsi/fsi_test.go
  fsi/init.go
  fsi/mapping.go
  fsi/status_test.go
  lib/fsi.go
Labels: FSI

#1020 fix(stats): gets stats with no structure
  api/datasets.go
  lib/datasets.go
Labels: fix

#1019 feat(stats): add histogram, mean, median to numeric stat
  api/testdata/api.snapshot
  go.mod
  go.sum
  lib/datasets_test.go
  stats/stats.go
  stats/stats_test.go
Labels: feat, stats

#1021 feat(fsi transform): skeletal support for transform scripts via FSI
  base/component/component.go
  base/component/kinds.go
  base/component/list_dir.go
  fsi/status.go
  go.mod
  go.sum
Labels: FSI, feat

#1022 fix(remove): Can remove a dataset if its working directory is missing
  cmd/remove_integration_test.go
  lib/datasets.go
Labels: FSI, fix

#1023 fix(rename): Allow rename for dataset with no history. Update .qri-ref
  base/ref.go
  cmd/rename_integration_test.go
  fsi/fsi.go
  fsi/fsi_test.go
  lib/datasets.go
  lib/fsi.go
Labels: fix

#1025 fix(init): Can init linked datasets with json format
  cmd/fsi_integration_test.go
  fsi/init.go
Labels: FSI, fix

#1026 chore(release): release v0.9.2
  CHANGELOG.md
  api/testdata/api.snapshot
  cmd/cmd_test.go
  cmd/save_test.go
  lib/lib.go
  startf/transform.go
Labels: chore

#1028 chore(version): bump to v0.9.3-dev post-release
  api/testdata/api.snapshot
  cmd/cmd_test.go
  cmd/save_test.go
  lib/lib.go
  p2p/p2p.go
  startf/transform.go
Labels: chore

#1027 fix(diff): Diff with no history returns a reasonable error message
  cmd/fsi_integration_test.go
  lib/diff.go
Labels: FSI, fix

#1029 refactor(oplog): Logstore interface
  base/log.go
  base/log_test.go
  identity/identity.go
  lib/datasets_test.go
  lib/lib.go
  lib/log.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/http.go
  logbook/logsync/http_test.go
  logbook/logsync/logsync.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p.go
  logbook/logsync/p2p_test.go
  logbook/oplog/log.fbs
  logbook/oplog/log.go
  logbook/oplog/log_bench_test.go
  logbook/oplog/log_test.go
  remote/remote.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/mem_repo.go
  stats/cache.go
Labels: logbook, refactor

#1032 test(p2p): TestMissingManifest should not hang when hashes change.
  p2p/dag_test.go
  p2p/test/p2ptest.go
Labels: network/p2p, test

#1031 feat(commit): Friendly commit descriptions based on deepdiff
  api/testdata/api.snapshot
  base/component/kinds.go
  base/dsdiff/.gitignore
  base/dsdiff/LICENSE
  base/dsdiff/README.md
  base/dsdiff/codecov.yml
  base/dsdiff/dsdiff.go
  base/dsdiff/dsdiff_test.go
  base/dsdiff/exp0.txt
  base/dsdiff/got0.txt
  base/dsdiff/test1.json
  base/dsdiff/testdata/newData.json
  base/dsdiff/testdata/newDescription.json
  base/dsdiff/testdata/newStructure.json
  base/dsdiff/testdata/newTitle.json
  base/dsdiff/testdata/newTransform.json
  base/dsdiff/testdata/newVisConfig.json
  base/dsdiff/testdata/orig.json
  base/dsdiff/testdata/structureJsonSchemaNew.json
  base/dsdiff/testdata/structureJsonSchemaOrig.json
  base/dsfs/dataset.go
  base/dsfs/dataset_test.go
  base/dsfs/subset/subset_test.go
  base/dsfs/testdata/all_fields/expect.dataset.json
  base/dsfs/testdata/cities/expect.dataset.json
  base/dsfs/testdata/craigslist/expect.dataset.json
  base/friendly/friendly.go
  base/friendly/friendly_test.go
  base/log_test.go
  base/save_test.go
  base/toqtype/toqtype.go
  base/toqtype/toqtype_test.go
  cmd/cmd_test.go
  cmd/log_integration_test.go
  cmd/remove_test.go
  cmd/save_test.go
  cmd/stringers.go
  cmd/test_runner.go
  lib/diff_test.go
  lib/log_test.go
  p2p/dag_test.go
Labels: fix

#1034 test(lib): refactor diff tests into testRunner
  go.mod
  go.sum
  lib/diff_test.go
  lib/lib_test.go
Labels: refactor, test
