Repository qri-io/qri, pull requests merged in 2019-02, with the labels that each got.

#683 feat(xlsx): initial support for xlsx file format
  Makefile
  actions/body.go
  actions/body_test.go
  actions/dataset.go
  actions/dataset_test.go
  api/datasets.go
  api/testdata/api.snapshot
  base/dataset.go
  base/dataset_test.go
  cmd/export.go
  cmd/remove.go
  cmd/remove_test.go
  cmd/save.go
  cmd/save_test.go
  lib/datasets.go
  lib/datasets_test.go
  lib/export.go
  lib/params.go
  lib/testdata/now_tf/transform.star
Labels: feat, in progress

#682 fix(save): Improve error message if new ds has no body or structure
  actions/dataset.go
  actions/dataset_test.go
Labels: in progress

#684 chore(release): release v0.7.0
  CHANGELOG.md
  api/testdata/api.snapshot
  lib/lib.go
Labels: chore, in progress

#686 fix(get): Apply format to get when using a selector
  api/testdata/api.snapshot
  lib/datasets.go
  lib/datasets_test.go
  lib/lib.go
Labels: CLI, fix, in progress

#687 feat(lib.Datasets.Save): add force flag to skip empty-commit checking
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  api/datasets.go
  base/base_test.go
  base/dataset.go
  base/dataset_test.go
  cmd/save.go
  lib/datasets.go
  lib/datasets_test.go
  lib/lib_test.go
  p2p/log_diff_test.go
  p2p/log_test.go
  repo/test/test_repo.go
Labels: API, CLI, feat, in progress

#689 test(lib.Datasets.Save): remove failing test case caused by qri-io/dataset#176
  lib/datasets_test.go
Labels: in progress, test

#688 fix(export): Overhaul export command
  base/entries.go
  base/entries_test.go
  base/render.go
  cmd/cmd_test.go
  cmd/export.go
  lib/datasets_test.go
  lib/export.go
Labels: in progress

#692 chore(fmt): Run go fmt, fix broken save_test, add descriptions
  actions/merge_events_test.go
  actions/transform_test.go
  base/entries.go
  cmd/cmd_test.go
  cmd/qri.go
  cmd/save_test.go
  lib/peers_test.go
  p2p/node.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/fs/refstore.go
  repo/gen/crypto_generator.go
  repo/graph_test.go
  repo/mem_repo.go
  repo/ref_test.go
  repo/repo.go
  repo/search/index.go
Labels: in progress

#691 fix(export): Test cases for export
  lib/export.go
  lib/export_test.go
Labels: in progress

#693 fix(export): Export --zip flag
  api/datasets.go
  api/testdata/api.snapshot
  cmd/cmd_test.go
  cmd/export.go
  lib/export.go
  lib/export_test.go
Labels: in progress

#694 fix(list): Improve usability of `list` command
  cmd/list.go
Labels: in progress

#695 fix(get): Get returns 404 if dataset is not found
  api/api_test.go
  api/registry.go
  api/registry_test.go
Labels: in progress

#696 fix(info): Remove the info command, list does it now
  cmd/cmd_test.go
  cmd/info.go
  cmd/qri.go
Labels: in progress

#697 fix(list): Flag --num-versions shows number of versions of each dataset
  actions/list_datasets.go
  actions/list_datasets_test.go
  api/registry_test.go
  base/dataset.go
  base/dataset_test.go
  cmd/list.go
  cmd/print.go
  lib/datasets.go
  lib/params.go
  p2p/datasets.go
Labels: in progress

#698 feat: overhauled diff command
  Makefile
  api/api_test.go
  api/dataset_test.go
  api/datasets.go
  api/log_test.go
  api/peers_test.go
  api/profile_test.go
  api/registry_test.go
  api/render_test.go
  api/search_test.go
  api/testdata/api.snapshot
  api/testdata/diffRequest.json
  api/testdata/diffRequestPlusMinusColor.json
  cmd/cmd_test.go
  cmd/diff.go
  cmd/diff_test.go
  cmd/publish_test.go
  cmd/qri.go
  lib/datasets.go
  lib/datasets_test.go
  lib/diff.go
  lib/diff_test.go
  repo/ref.go
  repo/ref_test.go
Labels: feat, in progress
