Repository qri-io/qri, pull requests merged in 2019-04, with the labels that each got.

#719 feat(remote): Send actual dag.Info to remote, perform dsync
  api/api.go
  api/remote.go
  api/remote_test.go
  api/testdata/api.snapshot
  base/fill/struct.go
  base/fill/struct_test.go
  cmd/connect.go
  config/api.go
  lib/file_test.go
  lib/remote.go
  lib/remote_test.go
Labels: in progress

#723 chore(cmd_test): Fix tests broken by 56b785
  cmd/cmd_test.go
Labels: in progress

#722 feat(remote): Retrieve sessionID & diff first, pass both to dsync
  api/api.go
  api/remote.go
  api/remote_test.go
  api/testdata/api.snapshot
  api/testdata/postRemoteRequest.json
  base/fill/struct.go
  base/fill/struct_test.go
  lib/params.go
  lib/remote.go
  lib/remote_test.go
Labels: in progress

#728 refactor(viz): Move code for adding "default viz" out of InferValues.
  actions/dataset.go
  api/testdata/api.snapshot
  base/dataset_prepare.go
  base/dataset_prepare_test.go
  base/render.go
  lib/lib.go
  p2p/p2p.go
Labels: in progress

#730 fix(render): supply default 'html' format if none exists
  base/render.go
Labels: fix

#732 refactor(p2p): Give node a CoreAPI accessor to simplify dependencies
  actions/dag.go
  actions/dataset.go
  api/api.go
  api/webapp.go
  lib/remote.go
  p2p/bootstrap.go
  p2p/node.go
  p2p/peers.go
Labels: in progress

#733 fix(ref): CanonicalizeProfile just handles renames all the time
  actions/list_datasets.go
  base/dataset.go
  lib/profile.go
  repo/ref.go
  repo/ref_test.go
Labels: in progress

#734 refactor(remote): Split remote push into mulitple actions. Add timeout.
  actions/remote.go
  actions/remote_test.go
  config/api.go
  lib/remote.go
Labels: in progress

#739 fix(list): qri list new command-line interface
  actions/list_datasets.go
  actions/list_datasets_test.go
  base/dataset.go
  base/dataset_test.go
  cmd/list.go
  lib/datasets.go
  lib/params.go
  p2p/datasets.go
Labels: in progress

#742 refactor(api): `/update` endpoint should return the updated dataset on success
  api/datasets.go
  base/fill/struct_test.go
  cmd/cmd_test.go
  cmd/save_test.go
Labels: in progress

#746 chore(makefile): add missing text package dep
  Makefile
Labels: chore, in progress

#744 refactor(lib.ConfigMethods): removes `lib.ConfigMethods` interface
  api/api.go
  api/profile.go
  cmd/config.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/get.go
  cmd/publish.go
  cmd/qri.go
  cmd/remove.go
  lib/config.go
  lib/lib.go
  lib/profile.go
Labels: in progress

#748 refactor(export, body api endpoints): fix bugs and add features to work with frontend
  api/dataset_test.go
  api/datasets.go
  api/open_api_2.yaml
  api/open_api_3.yaml
  api/testdata/api.snapshot
  lib/export.go
  lib/export_test.go
Labels: in progress

#745 feat(base/fill): Overhaul error handling
  base/fill/error_collector.go
  base/fill/path_value.go
  base/fill/path_value_test.go
  base/fill/struct.go
  base/fill/struct_test.go
  config/config_test.go
Labels: in progress

#749 fix(canonicalize): Correct peername when profileID matches
  repo/ref.go
  repo/ref_test.go
Labels: in progress

#750 fix(linux): Ignore errors from setting rlimit, needs root on linux
  cmd/system.go
Labels: in progress

#753 fix(docs): Building on windows, rpi, and brew install instructions
  README.md
Labels: in progress
