Repository qri-io/qri, pull requests merged in 2019-10, with the labels that each got.

#949 docs(CONTRIBUTOR.md): Update code of conduct link
  CONTRIBUTOR.md
Labels: docs, fix

#946 refactor(fsi): export to structure.json instead of schema.json by default
  api/fsi_test.go
  api/testdata/api.snapshot
  cmd/fsi_integration_test.go
  cmd/fsi_test.go
  fsi/mapping.go
  fsi/mapping_test.go
  fsi/status.go
  fsi/status_test.go
  lib/fsi.go
  lib/fsi_test.go
Labels: FSI, UX, refactor

#950 chore: remove bleve
  DEVELOPERS.md
  go.mod
  go.sum
  repo/fs/fs.go
  repo/fs/refstore.go
  repo/search/bleve.go
  repo/search/index.go
  repo/search/search.go
Labels: chore, refactor

#957 refactor(dsref): rename rev package to dsref, a home for all ref string parsing
  actions/recall.go
  api/datasets.go
  base/revisions.go
  base/revisions_test.go
  cmd/remove.go
  cmd/remove_test.go
  dsref/info.go
  dsref/ref.go
  dsref/ref_test.go
  dsref/rev.go
  dsref/rev_test.go
  go.sum
  lib/datasets.go
  lib/datasets_test.go
  repo/ref.go
  repo/ref_test.go
Labels: naming, refactor

#954 fix(init): add basic `structure.json` on `init`
  api/api.go
  api/fsi_test.go
  api/testdata/api.snapshot
  cmd/fsi_integration_test.go
  fsi/init.go
  fsi/init_test.go
  go.mod
  go.sum
  lib/fsi_test.go
Labels: fix, refactor

#948 refactor: use logbook, remove events code
  actions/actions_test.go
  actions/dataset.go
  actions/dataset_test.go
  actions/log.go
  actions/log_test.go
  actions/merge_events.go
  actions/merge_events_test.go
  api/log.go
  api/log_test.go
  base/dataset.go
  base/dataset_test.go
  base/log.go
  base/log_test.go
  cmd/cmd_test.go
  cmd/log.go
  cmd/log_test.go
  cmd/qri.go
  cmd/render_test.go
  cmd/stringers.go
  fsi/init.go
  go.mod
  go.sum
  lib/datasets.go
  lib/diff.go
  lib/lib.go
  lib/lib_test.go
  lib/log.go
  lib/log_test.go
  lib/peers_test.go
  lib/profile.go
  lib/update.go
  logbook/log/log.go
  logbook/log/log_test.go
  logbook/log/simulate_test.go
  logbook/logbook.go
  logbook/logbook_test.go
  p2p/events.go
  p2p/events_test.go
  p2p/log_diff.go
  p2p/log_diff_test.go
  p2p/node.go
  repo/events.go
  repo/events_test.go
  repo/fs/events.go
  repo/fs/fs.go
  repo/mem_repo.go
  repo/repo.go
  repo/test/test_refstore.go
  repo/test/test_repo.go
Labels: logbook, refactor, repo

#926 refactor(fsi): New core behavior for FSI, implemented using Component interface
  api/fsi_test.go
  base/fill/struct.go
  cmd/restore.go
  cmd/status.go
  fsi/body.go
  fsi/component/component.go
  fsi/component/component_test.go
  fsi/component/kinds.go
  fsi/component/list_dir.go
  fsi/component/list_dir_test.go
  fsi/component/testdata/commit.json
  fsi/fsi_test.go
  fsi/mapping.go
  fsi/mapping_test.go
  fsi/status.go
  fsi/status_test.go
  fsi/testdata/valid_mappings/all_in_dataset/dataset.yaml
  fsi/testdata/valid_mappings/some_json_components/body.csv
  fsi/testdata/valid_mappings/some_json_components/meta.json
  lib/datasets.go
  lib/fsi.go
Labels: FSI, refactor

#956 feat:(logsync): logsync synchronizes two datasets over a network
  actions/log.go
  actions/log_test.go
  api/api.go
  api/remote.go
  api/remote_test.go
  api/testdata/api.snapshot
  base/log.go
  base/log_test.go
  cmd/fetch.go
  cmd/fetch_test.go
  cmd/qri.go
  cmd/stringers.go
  lib/datasets.go
  lib/lib.go
  lib/lib_test.go
  lib/log.go
  lib/log_test.go
  lib/remote.go
  logbook/log/log.go
  logbook/log/log_test.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/http.go
  logbook/logsync/http_test.go
  logbook/logsync/logsync.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p.go
  logbook/logsync/p2p_test.go
  p2p/log.go
  p2p/log_diff.go
  p2p/log_test.go
  p2p/node.go
  p2p/test/p2ptest.go
  remote/client.go
  remote/remote.go
Labels: feat, logbook

#967 chore(dataset): Bump gomod version to get detect changes
  api/fsi_test.go
  api/testdata/api.snapshot
  go.mod
  go.sum
Labels: chore

#966 add logbook hooks to remote
  cmd/log.go
  go.mod
  go.sum
  lib/log.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/http.go
  logbook/logsync/logsync.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p.go
  logbook/oplog/log.fbs
  logbook/oplog/log.go
  logbook/oplog/log_test.go
  logbook/oplog/logfb/Book.go
  logbook/oplog/logfb/Log.go
  logbook/oplog/logfb/Logset.go
  logbook/oplog/logfb/OpType.go
  logbook/oplog/logfb/Operation.go
  logbook/oplog/simulate_test.go
  remote/client.go
  remote/context.go
  remote/make_api_test.go
  remote/remote.go
  remote/remote_test.go
  repo/ref.go
Labels: feat, remote

#969 fix(fill): Support setting int64
  base/fill/path_value.go
  base/fill/path_value_test.go
Labels: fix

#965 fix(actions, base): add `base.RemoveNVersionsFromStore` func
  actions/dataset.go
  actions/dataset_test.go
  base/base_test.go
  base/dataset.go
  base/dataset_test.go
  base/log_test.go
  go.mod
  go.sum
  lib/datasets.go
Labels: fix, refactor

#973 fix(remote): `DeleteDataset` func will now delete an entire dataset's history
  remote/client.go
  remote/remote.go
  remote/signature.go
  remote/signature_test.go
Labels: fix

#974 feat(readme): Readme component, prepare for removing viz
  base/dataset.go
  base/diff.go
  base/diff_test.go
  base/fill/struct.go
  base/fill/struct_test.go
  base/render.go
  base/revisions.go
  base/save.go
  cmd/dag.go
  cmd/diff.go
  cmd/get.go
  cmd/restore.go
  dsref/rev.go
  dsref/rev_test.go
  fsi/component/component.go
  fsi/component/field_id.go
  fsi/component/kinds.go
  fsi/component/list_dir.go
  fsi/component/list_dir_test.go
  fsi/mapping.go
  fsi/status_test.go
  fsi/testdata/valid_mappings/all_json_components/readme.md
  fsi/testdata/valid_mappings/some_json_components/readme.md
  go.mod
  go.sum
  lib/datasets.go
  lib/file.go
  lib/fsi.go
Labels: FSI, feat

#985 chore(mod): update ipfs & libp2p deps
  base/base_test.go
  base/dsfs/dataset.go
  base/dsfs/dataset_test.go
  base/dsfs/dstest/priv_key.go
  base/dsfs/transform_test.go
  cmd/fetch_test.go
  config/p2p.go
  config/test/test_peers.go
  go.mod
  go.sum
  lib/lib_test.go
  lib/peers.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/http.go
  logbook/logsync/logsync.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p.go
  logbook/logsync/p2p_test.go
  logbook/oplog/log.go
  logbook/oplog/log_test.go
  p2p/bootstrap.go
  p2p/connected.go
  p2p/datasets.go
  p2p/message.go
  p2p/node.go
  p2p/p2p.go
  p2p/peers.go
  p2p/ping.go
  p2p/profile.go
  p2p/profile_test.go
  p2p/qri_peers.go
  p2p/test/ipfs.go
  p2p/test/p2ptest.go
  p2p/test/testable_node_test.go
  p2p/wrapped_stream.go
  registry/profile.go
  registry/profile_test.go
  registry/profiles_test.go
  registry/regclient/profile.go
  registry/regclient/profile_test.go
  registry/regserver/handlers/profile_test.go
  registry/verify.go
  remote/client.go
  remote/signature.go
  repo/fs/fs.go
  repo/fs/profile_store.go
  repo/fs/profile_store_test.go
  repo/gen/crypto_generator.go
  repo/mem_repo.go
  repo/profile/id.go
  repo/profile/profile.go
  repo/profile/store.go
  repo/repo.go
  repo/repo_test.go
  repo/test/test_repo.go
Labels: chore

#986 fix(fsi): Don't output schema for default csv, many related fixes
  api/fsi_test.go
  base/component/component.go
  base/component/component_test.go
  base/component/field_id.go
  base/component/kinds.go
  base/component/list_dir.go
  base/component/list_dir_test.go
  base/component/testdata/commit.json
  cmd/dag.go
  cmd/diff.go
  cmd/fsi_integration_test.go
  cmd/get.go
  cmd/restore.go
  fsi/body.go
  fsi/init.go
  fsi/mapping.go
  fsi/mapping_test.go
  fsi/status.go
  lib/fsi.go
Labels: FSI, refactor

#987 chore(fmt): Run go fmt
  api/api_test.go
  api/datasets.go
  base/dataset.go
  base/dsfs/dsutil/dsutil_test.go
  base/ref_test.go
  base/save_test.go
  cmd/cmd_test.go
  fsi/mapping.go
  fsi/status.go
  lib/datasets_test.go
  lib/diff_test.go
  lib/export_test.go
  lib/fsi.go
  lib/remote.go
  p2p/dag.go
  p2p/test/testable_node_test.go
  remote/client_test.go
  remote/context.go
  repo/mem_repo.go
  repo/test/test_repo.go
Labels: chore

#988 feat(readme): Render readme component as html
  api/render.go
  api/render_test.go
  api/testdata/api.snapshot
  base/render_readme.go
  base/render_readme_test.go
  cmd/fsi_integration_test.go
  cmd/render.go
  cmd/render_test.go
  go.mod
  go.sum
  lib/render.go
  lib/render_test.go
Labels: feat
