Repository qri-io/qri, pull requests merged in 2020-03, with the labels that each got.

#1143 chore(circleci): add performance benchmarks on master branch push
  .circleci/config.yml
  .circleci/user_benchmarks.sh
Labels: chore, perf

#1147 test(cmd): Remove the old cmd integration test
  cmd/cmd_test.go
Labels: test

#1146 fix(history): Include the foreign field in history requests
  base/log.go
Labels: logbook

#1149 feat(diff): update to new deepdiff output, show context in diffs
  api/testdata/api.snapshot
  base/dsfs/dataset.go
  base/dsfs/dataset_test.go
  base/friendly/friendly.go
  base/friendly/friendly_test.go
  cmd/cmd_test.go
  cmd/diff.go
  cmd/diff_test.go
  cmd/fsi_integration_test.go
  cmd/print.go
  go.mod
  go.sum
  lib/datasets_test.go
  lib/diff.go
  lib/diff_test.go
  logbook/logbook.go
Labels: diff, feat

#1152 chore(release): Release v0.9.6
  CHANGELOG.md
  version/version.go
Labels: chore, fix

#1170 Document CLI args for fsi commands
  cmd/fsi.go
  cmd/fsi_test.go
  cmd/ref_select.go
Labels: CLI, docs

#1160 test(crypto): Don't use global crypto to fix tests exhausting peerInfos
  cmd/publish_test.go
  cmd/test_runner_test.go
  config/test/test_peers.go
  lib/integration_test.go
  registry/regserver/mock.go
  repo/test/generator.go
  repo/test/temp_repo.go
Labels: fix, test

#1156 test(logbook): Refactor then test the logbook foreign bit when listing
  base/base_test.go
  base/dataset_prepare_test.go
  base/dataset_test.go
  base/log_test.go
  dscache/convert_test.go
  logbook/temp_builder.go
Labels: logbook, test

#1171 docs(developer.md): add note about ulimit workaround
  DEVELOPERS.md
Labels: docs

#1177 feat(cmd): remove `--blank` option from `export`
  cmd/export.go
Labels: CLI, feat

#1184 docs(developers): fix url
  DEVELOPERS.md
Labels: docs

#1178 test(body): update expected message for missing host in url
  base/body_test.go
Labels: test

#1197 test(fsi): Written fsi components need to respect umask setting
  base/component/kinds.go
  cmd/fsi_integration_test.go
Labels: FSI, test

#1187 refactor(dsref): separating commit details from VersionInfo
  api/log.go
  api/testdata/api.snapshot
  base/log.go
  base/log_test.go
  base/remove.go
  cmd/fetch.go
  cmd/log.go
  cmd/save_test.go
  cmd/stringers.go
  dscache/convert.go
  dscache/convert_test.go
  dscache/def.fbs
  dscache/dscache.go
  dscache/dscachefb/RefEntryInfo.go
  dscache/fill_info.go
  dscache/mutator.go
  dsref/version_info.go
  dsref/version_info_test.go
  lib/datasets.go
  lib/log.go
  lib/log_test.go
  logbook/logbook.go
  logbook/logbook_test.go
  remote/peer_sync_client_test.go
  remote/remote_test.go
  repo/ref/convert.go
Labels: refactor

#1199 fix(registry): Prompt for password without echoing it to terminal
  cmd/cmd_test.go
  cmd/registry.go
  cmd/test_runner_test.go
Labels: fix, registry

#1202 docs(developers): add styleguide for CLI help
  DEVELOPERS.md
Labels: CLI, docs

#1201 chore(dag): Bump dag commit to get flaky test fixes
  go.mod
  go.sum
Labels: fix, test

#1198 feat(showcommit): Split cmd status-at-version into showcommit.
  api/api.go
  api/fsi.go
  api/fsi_test.go
  api/testdata/api.snapshot
  cmd/fsi_integration_test.go
  cmd/qri.go
  cmd/stats.go
  cmd/stats_test.go
  cmd/status.go
  cmd/whatchanged.go
  lib/fsi.go
Labels: FSI

#1204 fix(startf): script print statements print to stderr
  base/save.go
  cmd/cmd_test.go
  cmd/save.go
  cmd/save_test.go
  cmd/test_runner_test.go
  cmd/testdata/movies/tf_123.star
  lib/datasets.go
  repo/test/temp_repo.go
  startf/transform.go
  startf/transform_test.go
Labels: fix, starlark

#1208 fix(save): Cannot save new datasets if name contains upper-case characters
  api/testdata/api.snapshot
  cmd/cmd.go
  cmd/fsi_integration_test.go
  cmd/save.go
  cmd/save_test.go
  cmd/test_runner_test.go
  cmd/whatchanged.go
  dsref/parse.go
  dsref/parse_test.go
  lib/datasets.go
  lib/datasets_test.go
Labels: fix

#1210 fix(update): Change default port for update service
  config/testdata/default.yaml
  config/update.go
Labels: fix, test

#1211 test(fetch): Rewrite fetch test. Don't run connect, test expectations.
  cmd/fetch_test.go
  remote/remote.go
Labels: fix, test

#1203 fix(fsi): qri remove --all --force should not fail on low value files
  cmd/fsi_integration_test.go
  cmd/remove_integration_test.go
  fsi/fsi.go
  lib/datasets.go
Labels: fix

#1214 test(connect): Configure connect_test so that it uses its own ports
  cmd/connect_test.go
  cmd/test_runner_test.go
  lib/integration_test.go
Labels: test

#1213 fix(unlink): Fsi unlink handles more edge-cases, acts more sane.
  cmd/fsi.go
  cmd/fsi_integration_test.go
  cmd/test_runner_test.go
  dsref/parse.go
  fsi/fsi.go
  fsi/fsi_test.go
  lib/datasets.go
  lib/fsi.go
  repo/ref/convert.go
  repo/ref/convert_test.go
Labels: FSI, fix

#1191 feat(sql): run SQL queries using qri datasets as tables
  api/api.go
  api/sql.go
  api/sql_test.go
  api/testdata/api.snapshot
  base/body_test.go
  base/component/kinds.go
  base/dataset_prepare.go
  base/save.go
  cmd/cmd.go
  cmd/dag_test.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/log.go
  cmd/print.go
  cmd/qri.go
  cmd/remove.go
  cmd/remove_test.go
  cmd/rename.go
  cmd/rename_test.go
  cmd/render.go
  cmd/render_test.go
  cmd/save_test.go
  cmd/search.go
  cmd/search_test.go
  cmd/sql.go
  cmd/sql_test.go
  cmd/test_runner_test.go
  cmd/update.go
  cmd/update_test.go
  cmd/use.go
  cmd/use_test.go
  cmd/validate_test.go
  errors/errors.go
  errors/errors_test.go
  fsi/init.go
  go.mod
  go.sum
  lib/datasets.go
  lib/datasets_test.go
  lib/export.go
  lib/lib.go
  lib/lib_test.go
  lib/sql.go
  sql/preprocess/preprocess.go
  sql/preprocess/preprocess_test.go
  sql/qds/datasource.go
  sql/qds/datasource_test.go
  sql/sql.go
  sql/sql_test.go
  stats/stats_test.go
Labels: feat

#1223 fix(save): Infered name must start with a letter
  base/dataset_prepare.go
  cmd/save_test.go
  cmd/testdata/2015-09-16--2016-09-30.csv
  cmd/testdata/movies/2018_winners.csv
Labels: fix

#1221 fix(fetch): fetch should return DatasetLogItems and added tests
  api/log.go
  api/remote.go
  base/log.go
  base/log_test.go
  cmd/fetch.go
  cmd/fetch_test.go
  cmd/log.go
  lib/log.go
  lib/remote.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/http_test.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p_test.go
  repo/ref/convert.go
  repo/ref/convert_test.go
Labels: API, CLI, fix

#1229 fix(rpc): better error messages on RPC EOF
  lib/config.go
  lib/datasets.go
  lib/diff.go
  lib/export.go
  lib/fsi.go
  lib/lib.go
  lib/log.go
  lib/peers.go
  lib/profile.go
  lib/registry.go
  lib/remote.go
  lib/render.go
  lib/search.go
  lib/sql.go
  lib/update.go
Labels: UX, fix

#1230 fix export, remove dsutil package
  api/datasets.go
  api/root.go
  api/serialization.go
  api/serialization_test.go
  api/testdata/api.snapshot
  api/testdata/complete/body.csv
  api/testdata/complete/expect.dataset.json
  api/testdata/complete/input.dataset.json
  api/testdata/complete/rendered.html
  api/testdata/complete/template.html
  api/testdata/complete/transform.star
  api/testdata/dataset.yml
  base/archive/archive.go
  base/archive/archive_test.go
  base/archive/zip.go
  base/archive/zip_test.go
  base/dsfs/dsutil/dataset_yaml.go
  base/dsfs/dsutil/dataset_yaml_test.go
  base/dsfs/dsutil/dsutil.go
  base/dsfs/dsutil/dsutil_test.go
  lib/export.go
  lib/export_test.go
  lib/file.go
Labels: fix, refactor

#1222 feat(save): Friendly commit messages by analyzing head, body, and transform
  base/body_test.go
  base/dsfs/dataset.go
  base/dsfs/dataset_test.go
  base/dsfs/structure.go
  base/dsfs/transform_test.go
  base/friendly/friendly.go
  base/friendly/friendly_test.go
  cmd/cmd_test.go
  cmd/fetch_test.go
  cmd/log_integration_test.go
  cmd/save_test.go
  cmd/testdata/movies/tf_modified.star
  config/test/test_peers.go
  lib/diff_test.go
Labels: diff, feat

#1231 chore(subset): remove subset package
  base/dsfs/subset/subset.go
  base/dsfs/subset/subset_test.go
  base/dsfs/subset/testdata/movies/body.csv
  base/dsfs/subset/testdata/movies/input.dataset.json
Labels: chore

#1228 refactor(fsi): Remove fsi=true parameter, use FSIPath everywhere
  api/dataset_test.go
  api/datasets.go
  api/fsi.go
  api/fsi_test.go
  api/root.go
  api/testdata/api.snapshot
  base/ref.go
  cmd/fsi_integration_test.go
  cmd/get.go
  cmd/rename_integration_test.go
  cmd/save.go
  cmd/validate.go
  fsi/status.go
  lib/datasets.go
  lib/datasets_test.go
  lib/render.go
Labels: API, FSI
