Repository qri-io/qri, pull requests merged in 2020-12, with the labels that each got.

#1591 feat(version): add info from git and golang to qri version command
  Makefile
  README.md
  api/api.go
  cmd/version.go
  go.mod
  go.sum
  p2p/p2p.go
  remote/client.go
  startf/transform.go
  version/version.go
Labels: Breaking Change, chore, feat

#1576 chore(dockerfile): use two-image build
  Dockerfile
  Makefile
Labels: chore

#1593 chore(codecov): disable codecov github check annotations
  codecov.yml
Labels: chore

#1594 feat(save): support custom timestamps on commit
  base/dsfs/compute_fields.go
  base/dsfs/dataset.go
  base/dsfs/dataset_test.go
  cmd/testdata/movies/dataset.json
  repo/test/testdata/cities/input.dataset.json
  repo/test/testdata/counter/input.dataset.json
  repo/test/testdata/craigslist/input.dataset.json
  repo/test/testdata/flourinated_compounds_in_fast_food_packaging/input.dataset.json
  repo/test/testdata/movies/input.dataset.json
  repo/test/testdata/sitemap/input.dataset.json
Labels: base, feat

#1595 feat: save progress bars
  base/archive/archive_test.go
  base/dsfs/commit.go
  base/dsfs/compute_fields.go
  base/dsfs/dataset.go
  base/dsfs/dataset_test.go
  base/dsfs/testdata_test.go
  base/dsfs/transform_test.go
  base/save.go
  base/save_test.go
  cmd/print.go
  cmd/print_test.go
  cmd/qri.go
  cmd/save.go
  event/dataset.go
  event/event.go
  event/remote.go
  go.mod
  go.sum
  lib/lib.go
  lib/load_test.go
  lib/websocket.go
  remote/client.go
  remote/mock_client.go
  remote/remote_test.go
  repo/test/test_repo.go
Labels: feat, refactor

#1586 feat(api): change report API
  api/api.go
  api/datasets.go
  changes/changes.go
  changes/changes_test.go
  fsi/status.go
  go.mod
  go.sum
  lib/changes.go
  lib/lib.go
Labels: API, feat, stats

#1597 fix(save): remove dataset field computing deadlock
  base/dsfs/commit.go
  base/dsfs/compute_fields.go
  base/dsfs/structure.go
  go.mod
  go.sum
  logbook/logbook.go
  logbook/logbook_test.go
Labels: fix

#1599 fix(changes): column renames are properly handled now
  changes/changes.go
  changes/changes_test.go
Labels: API, fix

#1572 chore(p2p): update bootstrap addresses
  config/config.go
  config/migrate/migrate.go
  config/migrate/migrate_test.go
  config/migrate/testdata/two_to_three/qri_config.yaml
  config/p2p.go
  config/testdata/simple.yaml
Labels: chore, network/p2p, qri cloud

#1600 fix(logbook): Logsync validates that ref has correct profileID
  config/config.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/logsync.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p_test.go
Labels: logbook
