Repository qri-io/qri, pull requests merged in 2020-02, with the labels that each got.

#1087 feat(registry): add preview support to registry fetching
  api/api.go
  api/browse.go
  api/registry.go
  base/preview.go
  go.mod
  lib/browse.go
  lib/integration_test.go
  lib/lib.go
  lib/lib_test.go
  lib/registry.go
  registry/regclient/client.go
  registry/regserver/handlers/handlers.go
  registry/temp_registry_server/temp.go
  remote/client.go
  remote/remote.go
Labels: API, feat, registry

#1091 refactor(dsref): Add DetailedRef, representing dsref with additional details
  api/datasets.go
  api/fsi.go
  api/remote.go
  api/root.go
  api/testdata/api.snapshot
  base/base_test.go
  base/dataset_prepare.go
  base/ref_test.go
  cmd/cmd.go
  cmd/list.go
  cmd/rename_integration_test.go
  cmd/stringers.go
  dscache/convert.go
  dscache/convert_test.go
  dscache/dscache.go
  dsref/detailed_ref.go
  dsref/info.go
  lib/datasets.go
  lib/datasets_test.go
  lib/peers_test.go
  lib/profile.go
  p2p/resolve_ref.go
  p2p/test/p2ptest.go
  remote/mock_client.go
  remote/peer_sync_client.go
  remote/peer_sync_client_test.go
  remote/remote.go
  remote/remote_test.go
  remote/signature_test.go
  repo/parse.go
  repo/ref/convert.go
  repo/ref/dataset_ref.go
  repo/repo.go
  repo/serialize.go
  repo/store_test.go
  repo/test/spec/test_refstore.go
  repo/test/test_repo.go
Labels: API, refactor, repo

#1098 Update ipfs version number in readme
  README.md
Labels: docs

#1097 Fix broken link to registry in readme
  README.md
Labels: docs

#1095 feat(dscache): Dscache will get updated by save, if it exists in the repo
  base/save.go
  cmd/list.go
  cmd/save_test.go
  dscache/build/from_repo.go
  dscache/convert.go
  dscache/dscache.go
  dscache/dscache_test.go
  dscache/logbook_temp_builder_test.go
  dscache/mutator.go
  lib/datasets.go
  lib/lib.go
  lib/params.go
  logbook/action.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/logsync_test.go
  repo/buildrepo/build.go
  repo/fs/files.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/mem_repo.go
  repo/repo.go
  repo/test/test_repo.go
Labels: logbook

#1099 fix(remote): Handle error in order to avoid nil pointer
  lib/remote.go
Labels: fix, remote

#1100 test(circleci): Switch to 8 cpus for docker build on CI
  .circleci/config.yml
Labels: chore

#1101 fix(cli): remove extraneous logging from `qri registry prove`
  cmd/registry.go
  lib/registry.go
Labels: CLI, fix

#1102 refactor(dsref): Rename DetailedRef to VersionInfo
  api/datasets.go
  api/log.go
  api/remote.go
  api/testdata/api.snapshot
  base/log.go
  base/log_test.go
  cmd/fetch.go
  cmd/list.go
  cmd/log.go
  cmd/save_test.go
  cmd/stringers.go
  dscache/convert.go
  dscache/convert_test.go
  dscache/def.fbs
  dscache/dscache.go
  dscache/dscachefb/RefCache.go
  dscache/fill_info.go
  dsref/info.go
  dsref/version_info.go
  lib/datasets.go
  lib/datasets_test.go
  lib/log.go
  lib/log_test.go
  lib/remote.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/http_test.go
  repo/ref/convert.go
  repo/ref/dataset_ref.go
  repo/store.go
  repo/store_test.go
Labels: refactor

#1103 fix(dscache): Alphabetize refs in the dscache. Add tests.
  dscache/convert.go
  dscache/convert_test.go
  dscache/dscache.go
  go.mod
  go.sum
Labels: logbook

#1105 test(dscache): Test that BuildDscache will fill info from datasets
  dscache/convert_test.go
  go.mod
  go.sum
Labels: test

#1104 fix(regclient): update to new search endpoint, fix response ds.Name
  base/dataset.go
  cmd/cmd_test.go
  lib/remote.go
  registry/regclient/search.go
  registry/regserver/handlers/handlers.go
  registry/regserver/handlers/profile_test.go
  remote/remote.go
Labels: fix, registry

#1107 test(dscache): Align fields of dscache and VersionInfo. Test serialization
  dscache/builder.go
  dscache/convert.go
  dscache/def.fbs
  dscache/dscache_test.go
  dscache/dscachefb/RefCache.go
  dscache/fill_info.go
  dscache/logbook_temp_builder_test.go
  dsref/version_info.go
  repo/ref/convert.go
Labels: test

#1108 refactor(temp_registry_server): remove temp_registry_server
  registry/temp_registry_server/server.go
  registry/temp_registry_server/temp.go
Labels: chore, registry

#1109 test(testdata): Locate testdata directory without GOPATH.
  base/base_test.go
  base/dataset_test.go
  base/dsfs/dsutil/dsutil_test.go
  base/dsfs/dsutil/http_test.go
  base/dsfs/dsutil/zip_test.go
  lib/lib_test.go
  repo/test/generator.go
  repo/test/test_repo.go
Labels: test

#1106 fix(publish): Use Refselect for publish, so FSI works. Use dsref, add tests
  api/remote.go
  base/dataset.go
  base/log.go
  base/log_test.go
  base/ref.go
  cmd/publish.go
  cmd/publish_test.go
  lib/datasets.go
  lib/integration_test.go
  lib/log.go
  lib/registry.go
  lib/remote.go
  lib/update.go
  logbook/logsync/http.go
  logbook/logsync/p2p.go
  registry/regserver/handlers/handlers.go
  remote/remote_test.go
  repo/ref/convert.go
  repo/ref/dataset_ref.go
  repo/store.go
  repo/store_test.go
Labels: fix, registry

#1115 refactor(remote): move feed and preview interfaces into remote
  api/api.go
  api/registry.go
  api/remote.go
  dsref/version_info.go
  dsref/version_info_test.go
  lib/integration_test.go
  lib/registry.go
  lib/remote.go
  registry/regclient/client.go
  registry/regclient/search.go
  registry/regserver/handlers/handlers.go
  remote/browse.go
  remote/client.go
  remote/mock_client.go
  remote/peer_sync_client.go
  remote/peer_sync_client_test.go
  remote/remote.go
  remote/remote_test.go
Labels: refactor, registry, remote

#1118 Fix: Go version in Docker
  Dockerfile
Labels: chore

#1119 fix(remove): RemoveEntireDataset is better at cleaning up broken states
  api/testdata/api.snapshot
  base/dataset.go
  base/dataset_test.go
  base/remove.go
  base/remove_test.go
  cmd/remove.go
  cmd/remove_integration_test.go
  lib/datasets.go
  remote/remote.go
Labels: fix

#1121 fix(profileID): Disambiguate profileID construction to avoid subtle bugs
  api/datasets.go
  api/fsi.go
  api/root.go
  base/ref_test.go
  base/remove.go
  dscache/convert_test.go
  dscache/dscache_test.go
  p2p/node_test.go
  p2p/test/ipfs.go
  p2p/test/p2ptest.go
  remote/mock_client.go
  remote/peer_sync_client_test.go
  repo/profile/id.go
  repo/profile/id_test.go
  repo/store_test.go
  repo/test/spec/test_refstore.go
Labels: fix

#1122 fix(dsref): Parse dsref from strings. Use for rename and init.
  api/datasets.go
  api/testdata/api.snapshot
  base/dataset_prepare.go
  base/ref.go
  cmd/diff_test.go
  cmd/fsi_integration_test.go
  cmd/rename.go
  cmd/rename_test.go
  dsref/parse.go
  dsref/parse_test.go
  dsref/ref.go
  fsi/init.go
  lib/datasets.go
  lib/datasets_test.go
  lib/diff.go
  remote/remote.go
  repo/store.go
  repo/store_test.go
Labels: fix

#1125 feat(watchfs): Watched filesystem folders send dataset names as well
  api/websocket.go
  watchfs/event.go
  watchfs/watchfs.go
  watchfs/watchfs_test.go
Labels: FSI, feat

#1123 refactor(dscache): Rename dsInfo to entryInfo. Align with RefEntryInfo in fbs
  dscache/builder.go
  dscache/convert.go
  dscache/convert_test.go
  dscache/def.fbs
  dscache/dscache.go
  dscache/dscachefb/Dscache.go
  dscache/dscachefb/RefEntryInfo.go
  dscache/fill_info.go
  dscache/mutator.go
  dsref/version_info.go
Labels: refactor

#1128 feat(event): package event implements an event bus
  api/websocket.go
  event/event.go
  event/event_test.go
  event/fsi.go
  lib/fsi.go
  lib/lib.go
  watchfs/watchfs.go
Labels: feat

#1131 doc(building): Update instructions on building from source
  Makefile
  README.md
Labels: docs

#1134 fix(base): dry run works, doesn't write to logbook or dscache
  base/base_test.go
  base/save.go
  cmd/diff.go
  cmd/fsi.go
  cmd/get.go
  cmd/log.go
  cmd/publish.go
  cmd/remove.go
  cmd/render.go
  cmd/restore.go
  cmd/save.go
  cmd/validate.go
  p2p/test/ipfs.go
  repo/mem_repo.go
Labels: fix

#1135 fix(api): inline script bytes for get requests
  api/datasets.go
  api/root.go
  api/testdata/api.snapshot
  base/dsfs/dsutil/dsutil.go
Labels: API, fix

#1137 feat(api): support for dynamic dataset readme rendering
  api/api.go
  api/render.go
  lib/render.go
  lib/render_test.go
Labels: API, feat

#1139 chore(release): release v0.9.5
  CHANGELOG.md
  base/body_test.go
  version/version.go
Labels: chore, release process

#1141 chore(version): bump to version 0.9.6-dev
  version/version.go
Labels: chore

#1140 feat(dscache): Fill dscache when saving, using func pointer in logbook.
  base/save.go
  cmd/save.go
  cmd/save_test.go
  dscache/builder.go
  dscache/convert.go
  dscache/convert_test.go
  dscache/dscache.go
  dscache/dscache_test.go
  dscache/logbook_temp_builder_test.go
  dscache/mutator.go
  lib/datasets.go
  lib/lib.go
  logbook/action.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/logsync_test.go
  repo/buildrepo/build.go
  repo/fs/fs_test.go
  repo/mem_repo.go
  repo/test/test_repo.go
Labels: feat, logbook

#1142 refactor(event): wiring watchfs up to FSI events
  api/websocket.go
  dscache/dscache.go
  event/event.go
  event/event_test.go
  fsi/fsi.go
  fsi/fsi_test.go
  fsi/status_test.go
  lib/fsi.go
  lib/lib.go
  watchfs/watchfs.go
  watchfs/watchfs_test.go
Labels: event bus, refactor
