Repository qri-io/qri, pull requests merged in 2020-06, with the labels that each got.

#1361 feat(lib): subsystems can turn reference strings into datasets with a ParseLoadResolve function
  base/dataset.go
  base/ref.go
  base/transform_apply.go
  cmd/sql.go
  cmd/test_runner_test.go
  dscache/dscache.go
  dsref/load.go
  dsref/mem_resolver.go
  dsref/mem_resolver_test.go
  dsref/resolve.go
  dsref/resolve_test.go
  dsref/spec/load.go
  dsref/spec/resolve.go
  lib/datasets.go
  lib/fsi.go
  lib/integration_test.go
  lib/load.go
  lib/load_test.go
  lib/render.go
  lib/resolve.go
  lib/sql.go
  logbook/logbook.go
  logbook/logbook_test.go
  registry/regclient/client.go
  registry/regclient/client_test.go
  remote/peer_sync_client.go
  repo/fs/fs.go
  repo/mem_repo.go
  repo/test/temp_repo.go
  sql/qds/datasource.go
  sql/qds/datasource_test.go
  sql/sql.go
  startf/transform.go
  startf/transform_test.go
Labels: feat, lib

#1389 refactor: require migration, remove path factory
  cmd/cmd.go
  cmd/connect.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/fetch_test.go
  cmd/generate/generate.go
  cmd/qri.go
  cmd/ref_select.go
  cmd/ref_select_test.go
  cmd/setup.go
  cmd/test_runner_test.go
  cmd/use.go
  cmd/use_test.go
  config/config.go
  config/migrate/migrate.go
  config/migrate/migrate_test.go
  config/migrate/testdata/one_to_two/empty_ipfs_repo_v0.4.21.zip
  config/migrate/testdata/one_to_two/qri_config.yaml
  config/testdata/simple.yaml
  docs/docs.go
  go.mod
  go.sum
  lib/lib.go
  lib/lib_test.go
  lib/setup.go
  lib/setup_test.go
  repo/buildrepo/build.go
  repo/test/temp_repo.go
  repo/test/test_repo.go
Labels: refactor

#1393 refactor(store): drop Store from config, muxfs owns cafs.Filestore
  base/base_test.go
  base/body.go
  base/body_test.go
  base/dataset_test.go
  base/dsfs/dataset.go
  base/dsfs/dataset_test.go
  base/dsfs/package.go
  base/dsfs/transform_test.go
  base/log_test.go
  base/save.go
  base/save_test.go
  base/test_runner_test.go
  cmd/test_runner_test.go
  config/config.go
  config/config_test.go
  config/migrate/migrate.go
  config/store.go
  config/store_test.go
  config/testdata/default.yaml
  config/testdata/simple.yaml
  dscache/dscache_test.go
  dsref/spec/resolve.go
  go.mod
  go.sum
  lib/datasets.go
  lib/fsi.go
  lib/lib.go
  lib/lib_test.go
  lib/load.go
  lib/load_test.go
  lib/peers_test.go
  logbook/logbook_test.go
  logbook/logsync/logsync_test.go
  p2p/dag.go
  p2p/p2p_test.go
  p2p/test/ipfs.go
  remote/mock_client.go
  remote/peer_sync_client_test.go
  remote/remote_test.go
  repo/buildrepo/build.go
  repo/fs/fs.go
  repo/fs/fs_test.go
  repo/fs/refstore.go
  repo/mem_repo.go
  repo/mem_repo_test.go
  repo/refstore.go
  repo/refstore_test.go
  repo/repo.go
  repo/test/temp_repo.go
  repo/test/test_repo.go
Labels: lib, refactor

#1401 chore(deps): bump ipfs to v0.6.0
  go.mod
  go.sum
  repo/test/testdata/empty_ipfs_repo.zip
Labels: chore

#1395 refactor(api): adding support for cloud download
  api/api.go
  api/dataset_test.go
  api/datasets.go
  api/fsi_test.go
  api/get_test.go
Labels: refactor

#1403 feat(migrate): remove qri-only IPFS repo on config migration
  cmd/cmd.go
  config/migrate/migrate.go
  go.mod
  go.sum
  logbook/logbook.go
  p2p/test/ipfs.go
  repo/test/testdata/empty_ipfs_repo.zip
Labels: feat

#1408 fix(logbook): enforce single-author permissions on write methods
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/types.go
Labels: fix, logbook

#1409 feat(cmd): add migrate flag to connect command
  Dockerfile
  cmd/connect.go
  config/migrate/migrate.go
Labels: CLI, feat

#1404 fix(remove): When removing foreign dataset, remove the log
  base/remove.go
  cmd/remove_integration_test.go
  fsi/init.go
  lib/datasets.go
  lib/lib.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/logsync.go
  remote/mock_client.go
Labels: fix

#1413 fix(migrate): wait for repo to shut down after migration
  config/migrate/migrate.go
  go.sum
Labels: fix

#1414 refactor(fsi,base): remove calls to CanonicalizeDatasetRef from base.TransformApply, fsi package
  base/transform_apply.go
  dsref/load.go
  fsi/status.go
  lib/fsi.go
  lib/load.go
Labels: FSI, base, refactor

#1415 fix(AddDataset): preserve original path after `ResolveHeadRef`
  remote/peer_sync_client.go
Labels: fix

#1416 chore(libp2p2): adjust imports to point to non-deprecated packages
  logbook/logsync/p2p_test.go
  p2p/bootstrap.go
  p2p/connected.go
  p2p/discovery.go
  p2p/node.go
  p2p/peers.go
  p2p/profile_test.go
  p2p/qri_peers.go
  p2p/test/ipfs.go
  p2p/test/p2ptest.go
  p2p/test/testable_node_test.go
Labels: chore

#1418 fix(lib.Get): add FSIPath when ref.Path is prefixed with "/fsi"
  api/fsi_test.go
  lib/datasets.go
  lib/datasets_test.go
Labels: fix

#1421 chore: update qri & third party dependencies
  go.mod
  go.sum
Labels: chore

#1422 fix(rpc): shut down gracefully after completed RPC call
  api/api.go
  cmd/cmd.go
  cmd/fetch_test.go
  cmd/qri.go
  cmd/ref_select.go
  cmd/registry.go
  cmd/save.go
  cmd/whatchanged.go
  lib/integration_test.go
  lib/lib.go
  lib/rpc.go
  lib/rpc_test.go
Labels: RPC, fix

#1420 fix(regClient): ResolveRef now returns registry address
  registry/regclient/client.go
Labels: fix
