Repository qri-io/qri, pull requests merged in 2020-04, with the labels that each got.

#1238 refactor(test): test requires stable output
  cmd/fsi_integration_test.go
Labels: refactor, test

#1253 fix(save): If body is too large to diff, compare checksums
  base/dsfs/dataset.go
  cmd/save_test.go
Labels: fix

#1240 feat(cmd): added command to generate basic cmd autocompletion scripts
  cmd/add.go
  cmd/completion.go
  cmd/export.go
  cmd/qri.go
  cmd/render.go
  cmd/save.go
  cmd/validate.go
Labels: CLI, UX

#1239 fix(starlark): various cleanups to starlark runtime
  api/testdata/api.snapshot
  base/save.go
  go.mod
  go.sum
  lib/datasets.go
Labels: fix, starlark

#1252 feat(dscache): Dscache can be used for get command
  api/datasets.go
  api/fsi.go
  api/root.go
  base/dataset_prepare.go
  cmd/cmd_test.go
  cmd/fsi_integration_test.go
  cmd/get.go
  cmd/get_test.go
  cmd/list.go
  cmd/save.go
  dscache/dscache.go
  lib/datasets.go
  lib/datasets_test.go
  resolver/loader/loader.go
  resolver/mem_resolver.go
  resolver/mem_resolver_test.go
  resolver/resolver.go
Labels: feat

#1258 fix(transform): Re-open transform after friendly, so it writes to cafs
  base/dsfs/dataset.go
  cmd/cmd_test.go
  cmd/get_test.go
  cmd/save_test.go
  cmd/testdata/movies/tf_one_movie.star
Labels: fix

#1259 fix(watchfs): Methods need a mutex to avoid concurrent writes
  event/event.go
Labels: fix

#1261 fix(cmd): stats command works with an FSI directory
  cmd/stats.go
  cmd/stats_test.go
Labels: CLI, FSI, fix

#1260 fix(dsfs): fix dag structure, defend against bad DAGs
  api/testdata/api.snapshot
  base/base.go
  base/dataset.go
  base/dsfs/dataset.go
  base/dsfs/package.go
  base/log.go
  base/save.go
  cmd/add_test.go
  cmd/cmd_test.go
  cmd/fetch_test.go
  cmd/fsi_integration_test.go
  cmd/get_test.go
  cmd/log_integration_test.go
  cmd/save_test.go
  fsi/status.go
Labels: base, fix

#1265 chore(release): release v0.9.7
  CHANGELOG.md
  go.sum
  version/version.go
Labels: chore

#1272 fix(log): Timeout log retrieval so it won't hang
  base/log.go
  base/log_test.go
Labels: fix

#1269 Fix checkout dirs & allow checkout to specify directory on CLI
  cmd/checkout.go
  cmd/checkout_test.go
  fsi/fsi.go
  lib/fsi.go
Labels: CLI, FSI, fix

#1276 fix(parse): Allow hyphens in usernames and dataset names
  cmd/fsi_integration_test.go
  dsref/parse.go
  dsref/parse_test.go
Labels: fix

#1283 fix(setup): Don't crash when running `qri setup`
  cmd/qri.go
  cmd/setup.go
Labels: fix

#1287 fix(setup): Detect colors during init, which fixes setup
  cmd/qri.go
Labels: fix

#1284 feat(name): Generate valid dataset names, use in multiple places
  api/dataset_test.go
  api/testdata/api.snapshot
  base/dataset_prepare.go
  base/dataset_prepare_test.go
  cmd/checkout.go
  cmd/fsi_integration_test.go
  cmd/init.go
  cmd/save_test.go
  cmd/setup.go
  cmd/testdata/movies/TenMoviesAndLengths.csv
  cmd/testdata/movies/piraña_data.csv
  config/profile.go
  config/profile_test.go
  config/test_config.go
  dsref/generate.go
  dsref/generate_test.go
  dsref/parse.go
  go.mod
  lib/datasets_test.go
Labels: fix, naming

#1286 feat(save): Refactor save switches, use for file hint to inform commit messages
  base/base_test.go
  base/dataset_prepare.go
  base/dataset_test.go
  base/dsfs/dataset.go
  base/dsfs/dataset_test.go
  base/dsfs/transform_test.go
  base/save.go
  base/save_test.go
  cmd/add_test.go
  cmd/cmd_test.go
  cmd/fetch_test.go
  cmd/get_test.go
  cmd/log_integration_test.go
  cmd/save_test.go
  cmd/test_runner_test.go
  lib/datasets.go
  lib/diff_test.go
  lib/lib_test.go
  p2p/p2p_test.go
  remote/mock_client.go
  remote/remote_test.go
  repo/test/test_repo.go
Labels: fix, refactor

#1289 fix(export): handle ok-case of bad viz while connected
  base/archive/zip.go
Labels: fix

#1290 chore(release): release v0.9.8
  CHANGELOG.md
  version/version.go
Labels: chore

#1293 fix(save): Save change detection with readme works correctly
  base/dsfs/dataset.go
  cmd/fsi_integration_test.go
  cmd/qri.go
  cmd/save_test.go
  cmd/testdata/movies/even_more_movies.md
  cmd/testdata/movies/more_movies.md
  dsref/generate_test.go
  go.sum
Labels: FSI, fix

#1294 fix(repo): Construct temp repo using correct path
  cmd/cmd_test.go
  cmd/fsi_integration_test.go
  cmd/save_test.go
  cmd/test_runner_test.go
  repo/buildrepo/build.go
  repo/test/temp_repo.go
Labels: fix, test

#1304 feat(dscache): Dscache handles remove operations
  base/ref.go
  base/remove.go
  cmd/save_test.go
  dscache/dscache.go
  dscache/mutator.go
  lib/datasets.go
  lib/remote.go
  logbook/action.go
  logbook/logbook.go
Labels: feat, logbook

#1317 fix(init): Derive dataset name from directory base, not whole path
  cmd/init.go
Labels: FSI, fix

#1320 chore: remove update command, subsystem, api
  api/api.go
  api/update.go
  api/update_test.go
  cmd/cmd_test.go
  cmd/qri.go
  cmd/stringers.go
  cmd/stringers_test.go
  cmd/update.go
  cmd/update_test.go
  lib/lib.go
  lib/lib_test.go
  lib/update.go
  lib/update_test.go
  update/cron/cron.fbs
  update/cron/cron.go
  update/cron/cron_fbs/DatasetOptions.go
  update/cron/cron_fbs/Job.go
  update/cron/cron_fbs/JobType.go
  update/cron/cron_fbs/Jobs.go
  update/cron/cron_fbs/Options.go
  update/cron/cron_fbs/Secret.go
  update/cron/cron_fbs/ShellScriptOptions.go
  update/cron/cron_fbs/StrMapVal.go
  update/cron/cron_fbs/StringMapVal.go
  update/cron/cron_test.go
  update/cron/file_job_store.go
  update/cron/file_job_store_test.go
  update/cron/http.go
  update/cron/http_test.go
  update/cron/job.go
  update/cron/job_store.go
  update/cron/job_store_test.go
  update/cron/job_test.go
  update/cron/jobs.go
  update/cron/jobs_test.go
  update/cron/testdata/test.sh
  update/daemon.go
  update/daemon_darwin.go
  update/testdata/hello.sh
  update/update.go
  update/update_test.go
Labels: chore
