Repository qri-io/qri, pull requests merged in 2020-10, with the labels that each got.

#1549 feat(progress): enable websocket push pull events
  lib/websocket.go
Labels: enhancement

#1550 fix(event bus): encoded fields use lower-case names in JSON
  event/dataset.go
  event/filesystem.go
  event/remote.go
Labels: event bus, fix

#1553 fix(connect): only run `DoSetup` if there is existing repo
  cmd/connect.go
  lib/lib.go
  lib/setup.go
Labels: fix

#1554 fix(watchfs): `WatchAllFSIPaths` needs to call `watchPaths`
  watchfs/watchfs.go
  watchfs/watchfs_test.go
Labels: fix

#1556 test(windows): Fix lib/ unit tests for Windows platform
  lib/fsi.go
  lib/fsi_test.go
  lib/lib.go
  lib/lib_test.go
  lib/test_runner_test.go
Labels: platform/windows, test

#1560 fix(api): Fix api test for health check by ignoring version number
  api/api_test.go
  api/testdata/api.snapshot
Labels: API, test

#1558 chore(release): release v0.9.13
  CHANGELOG.md
  version/version.go
Labels: chore, fix

#1561 Spelling of Collission corrected
  api/context.go
Labels: docs

#1562 fix(fill): Map keys are case-insensitive, handle maps recursively
  base/fill/path_value.go
  base/fill/path_value_test.go
  base/fill/struct_test.go
  config/config_test.go
  lib/fsi.go
  lib/lib_test.go
Labels: fix

#1569 feat(stats): stats based on sketch/probabalistic data structures
  api/testdata/api.snapshot
  cmd/stats_test.go
  go.mod
  go.sum
  lib/datasets_test.go
  stats/histosketch/histosektch_test.go
  stats/histosketch/histosketch.go
  stats/stats.go
  stats/stats_test.go
Labels: diff, feat, perf

#1570 refactor(api): better health check handling for API
  api/api.go
  api/testdata/api.snapshot
Labels: API, refactor
