Repository qri-io/qri, pull requests merged in 2021-06, with the labels that each got.

#1797 feat(workflow): fleshes out `workflow.Store`, `Trigger` and `Hook` interfaces, expands `Workflow` struct
  automation/hook/hook.go
  automation/hook/runtime_hook.go
  automation/hook/runtime_hook_test.go
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/spec/hook.go
  automation/spec/store.go
  automation/spec/trigger.go
  automation/trigger/runtime_trigger.go
  automation/trigger/runtime_trigger_test.go
  automation/trigger/trigger.go
  automation/workflow/store.go
  automation/workflow/store_test.go
  automation/workflow/workflow.go
  automation/workflow/workflow_test.go
Labels: feat

#1805 fix(readme): readme urls are linked properly now
  auth/key/store.go
  base/render_readme.go
  profile/store.go
Labels: fix

#1807 fix(api): don't error when running connect with disabled p2p
  api/api.go
  api/api_test.go
  cmd/fetch_test.go
  lib/lib.go
Labels: API, fix

#1808 feat(base): support progress in save, shorter stats keys, support NDJSON
  api/http_client_test.go
  api/testdata/http_client/list.json
  base/body.go
  base/dsfs/compute_fields.go
  base/dsfs/compute_fields_test.go
  base/dsfs/dataset_test.go
  base/dsfs/testdata/craigslist/expect.dataset.json
  base/dsfs/testdata/movies/expect.dataset.json
  cmd/cmd_test.go
  cmd/get_test.go
  cmd/log_integration_test.go
  cmd/log_test.go
  cmd/pull_test.go
  cmd/remove_test.go
  cmd/save_test.go
  cmd/testdata/expect/TestSaveState.json
  cmd/testdata/expect/TestSaveThenOverrideMetaAndTransformAndViz.json
  cmd/testdata/expect/TestSaveThenOverrideMetaComponent.json
  cmd/testdata/expect/TestSaveThenOverrideTransform.json
  cmd/testdata/expect/TestSaveThenOverrideViz.json
  cmd/testdata/expect/TestSaveTwoComponents.json
  cmd/testdata/expect/TestSaveWithBodyThenAddMetaAndSmallBodyChange.json
  cmd/testdata/expect/TestSaveWithBodyThenAddMetaComponent.json
  go.mod
  go.sum
  lib/collection_test.go
  lib/datasets.go
  lib/datasets_test.go
  lib/testdata/cities.stats.json
  lib/testdata/sitemap.stats.json
Labels: base, feat

#1803 feat(run): add `run.Store` interface, spec tests, and implement `run.MemStore`
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/run/run.go
  automation/run/store.go
  automation/run/store_test.go
  automation/spec/run.go
  automation/spec/workflow_store.go
  automation/workflow/store.go
  automation/workflow/store_test.go
  automation/workflow/workflow.go
  base/params/list.go
  base/params/list_test.go
  lib/datasets.go
Labels: feat

#1815 refactor(connect): re-work connection detail printout for qri connect
  Makefile
  api/api.go
  config/config.go
Labels: CLI, refactor

#1802 local collection migrates from repo, updates via event bus subscriptions
  collection/collection.go
  collection/collection_test.go
  collection/migrate.go
  collection/migrate_test.go
  collection/spec/collection.go
Labels: collection, feat

#1814 feat(trigger): `Trigger`, `Listener`, and `Source` interfaces, as well as `AssertTriggerListener` spec tests
  automation/hook/hook.go
  automation/hook/runtime_hook.go
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/spec/hook.go
  automation/spec/trigger.go
  automation/trigger/runtime.go
  automation/trigger/runtime_test.go
  automation/trigger/runtime_trigger.go
  automation/trigger/runtime_trigger_test.go
  automation/trigger/trigger.go
  automation/workflow/workflow.go
  event/workflow.go
Labels: feat
