Repository qri-io/qri, pull requests merged in 2021-11, with the labels that each got.

#1955 chore(starlib): Bump starlib for dataframe fix
  docs/go.sum
  go.mod
  go.sum
Labels: chore

#1960 feat(transform): Recover from transform panics, return as error
  transform/startf/transform.go
Labels: feat

#1965 fix(lib): go routine to assure instance context cancellation now closes properly
  lib/lib.go
Labels: fix

#1951 feat(transform): Control flow graphs built by starlark analyzer
  transform/staticlark/analyze.go
  transform/staticlark/call_graph.go
  transform/staticlark/call_graph_test.go
  transform/staticlark/control_flow.go
  transform/staticlark/control_flow_test.go
  transform/staticlark/functions.go
  transform/staticlark/functions_test.go
  transform/staticlark/testdata/loop_funcs.star
  transform/staticlark/testdata/some_funcs.star
  transform/staticlark/unit.go
Labels: feat

#1966 feat(automation): `RunQueue` interface to sync & cancel runs
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/run/run.go
  automation/run_queue.go
  automation/run_queue_test.go
Labels: feat, refactor

#1972 feat(transform): Detect terminal size, pass it to transform to affect DataFrame rendering
  automation/orchestrator.go
  automation/orchestrator_test.go
  cmd/apply.go
  cmd/system.go
  cmd/system_windows.go
  docs/go.sum
  go.mod
  go.sum
  lib/automation.go
  lib/automation_test.go
  lib/datasets.go
  lib/lib.go
  transform/startf/ds/bound.go
  transform/startf/ds/dataset.go
  transform/startf/ds/dataset_test.go
  transform/startf/sandbox.go
  transform/startf/transform.go
  transform/transform.go
  transform/transform_test.go
Labels: feat

#1978 feat(api): POST a body file to the new `/ds/save/form` endpoint to create a dataset
  api/api.go
  api/endpoints.go
  api/handlers.go
  api/handlers_test.go
  api/testdata/cities/dataset.yml
  api/testdata/cities/readme.md
  api/testdata/cities/template.html
  api/testdata/cities/transform.star
  api/testdata/expect/TestSaveByUpload.test_ds.json
  lib/datasets.go
  lib/datasets_test.go
Labels: feat, API

#1979 fix(RunQueue): scope events to the ownerID of the run
  automation/run_queue.go
Labels: fix

#1980 fix(lib): `/get` endpoint should return preview if no `selector` given
  api/testdata/expect/TestDatasetGet.test_ds.json
  cmd/get_test.go
  cmd/pull_test.go
  lib/datasets.go
  lib/datasets_test.go
Labels: fix

#1983 fix(api): Restore the WritePageResponse method
  api/util/responses.go
  api/util/responses_test.go
Labels: fix, API
