Repository qri-io/qri, pull requests merged in 2021-09, with the labels that each got.

#1900 refactor(*): add "aggregate" fields to `VersionInfo` & listen for cloud event in `collection`
  api/handlers.go
  api/open_api_3.yaml
  api/spec/testdata/aggregate.json
  cmd/cmd_test.go
  cmd/list.go
  cmd/stringers.go
  collection/collection.go
  collection/collection_assert_test.go
  dscache/dscache.go
  dscache/dscachefb/RefEntryInfo.go
  dsref/version_info.go
  event/dataset.go
  event/remote.go
  lib/collection.go
  lib/collection_test.go
  lib/http/api.go
  lib/params.go
  logbook/logbook.go
  repo/ref/convert.go
Labels: refactor, API

#1906 fix(collection): clean up run tracking
  collection/collection.go
  collection/collection_assert_test.go
  dscache/dscache.go
  event/dataset.go
  event/logbook.go
  event/transform.go
  logbook/logbook.go
  transform/transform.go
  transform/transform_test.go
Labels: fix

#1909 fix(collection): use `logbook` to fill in missing run and commit count data during `collection` migration
  collection/migrate.go
  collection/migrate_test.go
  logbook/logbook.go
Labels: fix

#1905 Overhaul Transform API
  api/spec/testdata/automation.json
  automation/workflow/wftest/testdata/no_changes/input.dataset.json
  automation/workflow/wftest/testdata/now/input.dataset.json
  automation/workflow/wftest/wftest.go
  cmd/cmd_test.go
  cmd/testdata/expect/TestSaveThenOverrideMetaAndTransformAndViz.json
  cmd/testdata/expect/TestSaveThenOverrideTransform.json
  cmd/testdata/movies/tf.star
  cmd/testdata/movies/tf_123.star
  cmd/testdata/movies/tf_add_row.star
  cmd/testdata/movies/tf_modified.star
  cmd/testdata/movies/tf_one_movie.star
  cmd/testdata/movies/tf_set_len.star
  cmd/testdata/movies/tf_set_meta.star
  cmd/testdata/movies/tf_use_config_secret.star
  docs/go.sum
  go.mod
  go.sum
  lib/automation.go
  lib/automation_test.go
  lib/datasets.go
  lib/integration_test.go
  lib/testdata/cities_2/add_city.star
  lib/testdata/tf/transform.star
  transform/startf/context/context.go
  transform/startf/context/context_test.go
  transform/startf/context/testdata/test.star
  transform/startf/ds/bound.go
  transform/startf/ds/dataset.go
  transform/startf/ds/testdata/test.star
  transform/startf/exec_step.go
  transform/startf/sandbox.go
  transform/startf/sandbox_test.go
  transform/startf/testdata/dataset_body_get.star
  transform/startf/testdata/dataset_body_set.star
  transform/startf/testdata/fetch.star
  transform/startf/testdata/load_ds.star
  transform/startf/testdata/meta_title.star
  transform/startf/testdata/tf.star
  transform/startf/transform.go
  transform/startf/transform_test.go
  transform/transform.go
  transform/transform_test.go
Labels: Breaking Change, transforms

#1914 feat(key): add key-to-base64 encoder and decoder functions
  auth/key/gen.go
  auth/key/key.go
  auth/key/key_test.go
  base/base_test.go
  base/dsfs/dstest/priv_key.go
  config/p2p.go
  config/p2p_test.go
  lib/lib_test.go
  lib/registry.go
  logbook/logsync/http.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p.go
  logbook/oplog/log_test.go
  p2p/node.go
  p2p/test/ipfs.go
  p2p/test/testable_node_test.go
  profile/profile.go
  registry/profile.go
  registry/profiles_test.go
  registry/regclient/profile_test.go
  registry/regserver/handlers/profile_test.go
  registry/verify.go
  remote/registry/profile.go
  remote/registry/profiles_test.go
  remote/registry/regclient/profile_test.go
  remote/registry/regserver/handlers/profile_test.go
  remote/registry/verify.go
  remote/signature.go
Labels: feat, PKI

#1911 fix(transform): need to pass down InitIDs to `transform.Commit`
  lib/datasets.go
  transform/transform.go
  transform/transform_test.go
Labels: fix

#1910 refactor(startf): transforms should return a dataset with the `Structure.Entries`
  transform/startf/ds/dataset.go
  transform/startf/testdata/set_meta.star
  transform/startf/transform.go
  transform/startf/transform_test.go
  transform/transform_test.go
Labels: refactor

#1916 fix(transform): transforms default to CSV format
  cmd/cmd_test.go
  cmd/save_test.go
  lib/automation_test.go
  transform/startf/ds/dataset.go
  transform/startf/transform_test.go
  transform/transform_test.go
Labels: fix, transforms

#1917 overhaul crypto generator API, support Ed25519 in JWT token construct/verify
  auth/auth_test.go
  auth/key/gen.go
  auth/key/test/keys.go
  auth/key/test/keys_test.go
  auth/token/token.go
  cmd/cmd.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/generate/generate.go
  cmd/qri.go
  cmd/setup.go
  cmd/setup_test.go
  cmd/test_runner_test.go
  docs/docs.go
  docs/go.mod
  lib/lib_test.go
  lib/setup.go
  lib/setup_test.go
  profile/id.go
  repo/test/generator.go
  repo/test/temp_repo.go
Labels: feat, PKI

#1920 chore(deps): bump starlib dep
  docs/go.sum
  go.mod
  go.sum
Labels: chore, starlark

#1924 refactor(save): datasets no longer require body to save
  base/save.go
  base/save_test.go
  docs/go.sum
  go.mod
  go.sum
  lib/datasets_test.go
Labels: refactor, save path

#1921 feat(websocket): add process to authenticate websocket connections
  api/api.go
  lib/lib.go
  lib/websocket.go
  lib/websocket/websocket.go
  lib/websocket/websocket_test.go
  lib/websocket_test.go
Labels: feat

#1926 fix(websocket): request context causes early cancellation
  lib/websocket/websocket.go
Labels: fix

#1929 fix(lib): hack - deploy path needs to create a `runID`
  lib/automation.go
Labels: fix

#1930 fix(lib): scope the `lib.apply` context
  lib/automation.go
Labels: fix
