Repository qri-io/qri, pull requests merged in 2021-12, with the labels that each got.

#1977 feat(staticlark): Dataflow analysis for sensitive data
  transform/staticlark/analyze.go
  transform/staticlark/call_graph.go
  transform/staticlark/control_flow_test.go
  transform/staticlark/dataflow.go
  transform/staticlark/dataflow_test.go
  transform/staticlark/environment.go
  transform/staticlark/functions.go
  transform/staticlark/testdata/call_trace.star
  transform/staticlark/testdata/safety_funcs.star
  transform/staticlark/unit.go
  transform/staticlark/unit_test.go
Labels: feat

#1986 docs(cursor): Describe Cursor and how it's used for pagination.
  lib/cursor.go
Labels: docs

#1987 fix(lib): use `username` parameter in `lib.List`
  lib/collection.go
Labels: fix

#1993 fix(collection): make event handler use independent ctx
  collection/collection.go
Labels: fix

#1995 feat(transform): Analyze `if` statements by unioning each branch
  transform/staticlark/call_graph_test.go
  transform/staticlark/control_flow.go
  transform/staticlark/control_flow_test.go
  transform/staticlark/dataflow.go
  transform/staticlark/dataflow_test.go
  transform/staticlark/environment.go
  transform/staticlark/functions_test.go
  transform/staticlark/testdata/control_funcs.star
  transform/staticlark/testdata/some_funcs.star
Labels: feat
