Repository qri-io/qri, pull requests merged in 2021-08, with the labels that each got.

#1852 refactor(workflow): supply context to all workflow store ops
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/spec/workflow_store.go
  automation/workflow/filestore.go
  automation/workflow/filestore_test.go
  automation/workflow/store.go
  lib/automation.go
Labels: refactor

#1856 refactor(lib): add lib.OptOrchestrator
  lib/lib.go
Labels: automation, refactor

#1860 refactor(wf_store): pass in ownerID to enable filtering
  automation/orchestrator.go
  automation/spec/workflow_store.go
  automation/workflow/filestore.go
  automation/workflow/store.go
  collection/collection_test.go
Labels: automation, refactor

#1866 fix(json): fix JSON body string escape sequence handling
  go.mod
  go.sum
Labels: fix, dataset

#1849 feat(lib): add lib `Run` and lib `Workflow` methods and endpoints
  api/api_test.go
  api/open_api_3.yaml
  api/spec/testdata/automation.json
  api/test_runner_test.go
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/workflow/wftest/testdata/no_changes/expect.workflow.json
  automation/workflow/wftest/testdata/no_changes/input.dataset.json
  automation/workflow/wftest/testdata/no_changes/input.workflow.json
  automation/workflow/wftest/testdata/now/expect.workflow.json
  automation/workflow/wftest/testdata/now/input.dataset.json
  automation/workflow/wftest/testdata/now/input.workflow.json
  automation/workflow/wftest/wftest.go
  automation/workflow/wftest/wftest_test.go
  automation/workflow/workflow.go
  lib/automation.go
  lib/automation_test.go
  lib/http/api.go
  lib/lib.go
Labels: feat

#1867 fix(api): make sure endpoints are of type APIEndpoint
  lib/http/api.go
Labels: fix, API

#1864 refactor(dsfs): replace qfs.AddingFS with qfs.MerkleDagStore, support save over HTTP-backed IPFS connection
  .circleci/config.yml
  base/archive/archive_test.go
  base/archive/zip_test.go
  base/dsfs/body.go
  base/dsfs/body_test.go
  base/dsfs/commit.go
  base/dsfs/compute_fields.go
  base/dsfs/compute_fields_test.go
  base/dsfs/dataset.go
  base/dsfs/dsfs.go
  base/dsfs/dsfs_test.go
  base/dsfs/file.go
  base/dsfs/load.go
  base/dsfs/load_test.go
  base/dsfs/meta.go
  base/dsfs/package.go
  base/dsfs/readme.go
  base/dsfs/stats.go
  base/dsfs/structure.go
  base/dsfs/testdata/zip/exported.zip
  base/dsfs/transform.go
  base/dsfs/transform_test.go
  base/dsfs/viz.go
  base/dsfs/write.go
  base/dsfs/write_test.go
  base/friendly/friendly.go
  base/save_test.go
  cmd/cmd_test.go
  cmd/fsi_integration_test.go
  cmd/get_test.go
  cmd/log_integration_test.go
  cmd/log_test.go
  cmd/pull_test.go
  cmd/save_test.go
  cmd/testdata/expect/TestSaveState.json
  cmd/testdata/expect/TestSaveThenOverrideMetaAndTransformAndViz.json
  cmd/testdata/expect/TestSaveThenOverrideMetaComponent.json
  cmd/testdata/expect/TestSaveThenOverrideTransform.json
  cmd/testdata/expect/TestSaveThenOverrideViz.json
  cmd/testdata/expect/TestSaveTwoComponents.json
  cmd/testdata/expect/TestSaveWithBodyThenAddMetaAndSmallBodyChange.json
  cmd/testdata/expect/TestSaveWithBodyThenAddMetaComponent.json
  docs/go.mod
  docs/go.sum
  dsref/rev.go
  dsref/rev_test.go
  go.mod
  go.sum
  p2p/dag_test.go
  p2p/node.go
  p2p/test/ipfs.go
  remote/client_test.go
  remote/remote_test.go
  remote/testdata/expect/TestClientFeedsAndPreviews.json
  stats/stats.go
  stats/stats_test.go
Labels: feat, refactor, base

#1871 fix: deploy panics, double version removal, collection clean up
  collection/spec/collection.go
  docs/go.sum
  event/dataset.go
  go.mod
  go.sum
  lib/automation.go
  lib/datasets.go
  p2p/node.go
Labels: fix

#1876 refactor(logbook): support multi tenancy
  api/fsi_test.go
  api/testdata/expect/TestDatasetGet.test_ds.json
  base/log.go
  base/log_test.go
  base/ref.go
  base/remove.go
  base/remove_test.go
  base/save.go
  base/save_test.go
  base/test_runner_test.go
  cmd/fsi_integration_test.go
  cmd/get_test.go
  cmd/print.go
  cmd/pull_test.go
  cmd/remove_integration_test.go
  cmd/save.go
  cmd/test_runner_test.go
  dscache/convert_test.go
  dscache/dscache_test.go
  dsref/mem_resolver_test.go
  dsref/spec/resolve.go
  dsref/version_info.go
  fsi/init.go
  lib/automation.go
  lib/automation_test.go
  lib/datasets.go
  lib/datasets_test.go
  lib/diff_test.go
  lib/lib.go
  lib/load.go
  lib/load_test.go
  lib/registry.go
  lib/scope.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/http_test.go
  logbook/logsync/logsync.go
  logbook/logsync/logsync_test.go
  logbook/logsync/p2p_test.go
  logbook/oplog/log.go
  logbook/oplog/log_test.go
  logbook/temp_builder.go
  logbook/types.go
  p2p/resolve_ref_test.go
  p2p/test/ipfs.go
  profile/author.go
  profile/profile.go
  profile/test/profiles.go
  remote/client_test.go
  remote/mock/client.go
  remote/remote_test.go
  remote/server.go
  repo/buildrepo/build.go
  repo/fs/fs_test.go
  repo/mem_repo.go
  repo/mem_repo_test.go
  repo/test/test_repo.go
Labels: refactor, logbook

#1875 fix(lib): `lib.Run` should mirror `lib.Deploy` return ASAP behavior
  lib/automation.go
  lib/automation_test.go
Labels: refactor, fix

#1877 refactor(collection): rely on `ETAutomationWorkflowCreated` events
  automation/orchestrator.go
  collection/collection.go
  collection/spec/collection.go
  event/automation.go
Labels: refactor

#1879 refactor(multi tenancy): plumb authors into various codepaths
  base/base_test.go
  base/dataset_test.go
  base/ref.go
  base/ref_test.go
  base/save.go
  base/save_test.go
  base/test_runner_test.go
  changes/changes_test.go
  cmd/test_runner_test.go
  collection/migrate.go
  lib/access.go
  lib/datasets.go
  lib/lib_test.go
  lib/registry.go
  lib/remote.go
  p2p/p2p_test.go
  remote/client.go
  remote/client_test.go
  remote/remote_test.go
Labels: access control

#1881 fix(logbook): resolve by AuthorID should always use external identifiers
  logbook/oplog/log.go
Labels: fix, logbook

#1883 fix(collection): maintain `WorkflowID` and run information in collection
  collection/collection.go
Labels: fix

#1886 feat(logbook): add `logPutter` interface for transactional saves
  logbook/logbook.go
Labels: feat, logbook

#1889 test(collection): tests for workflow & new version creation
  collection/spec/collection.go
  lib/automation.go
Labels: test

#1890 feat(collection): expand `WritableSet` interface, add option to pass in custom `WritableSet`
  automation/orchestrator.go
  base/dataset_test.go
  collection/collection.go
  collection/collection_assert_test.go
  collection/collection_test.go
  collection/migrate.go
  collection/migrate_test.go
  lib/collection.go
  lib/lib.go
  lib/lib_test.go
  lib/scope.go
  remote/mock/client.go
Labels: feat, refactor
