Repository qri-io/qri, pull requests merged in 2021-03, with the labels that each got.

#1653 feat(lib): Dispatch methods call, used by FSI
  api/api.go
  api/fsi.go
  api/fsi_test.go
  api/testdata/api.snapshot
  api/util/errors.go
  cmd/checkout.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/fsi.go
  cmd/fsi_integration_test.go
  cmd/init.go
  cmd/qri.go
  cmd/ref_select.go
  cmd/restore.go
  cmd/save.go
  cmd/status.go
  cmd/test_runner_test.go
  cmd/whatchanged.go
  fsi/status.go
  lib/api.go
  lib/datasets.go
  lib/datasets_test.go
  lib/dispatch.go
  lib/fsi.go
  lib/fsi_test.go
  lib/http.go
  lib/lib.go
  lib/lib_test.go
  lib/rpc.go
  lib/scope.go
  lib/test_runner_test.go
Labels: Breaking Change, lib

#1668 fix(http): fix httpClient error checking
  lib/datasets_test.go
  lib/dispatch.go
  lib/http.go
  lib/params.go
Labels: RPC

#1673 chore(deps): update to latest version of `dataset` package
  go.mod
  go.sum
Labels: chore

#1667 feat: "access token" command, dispatch session support
  api/api.go
  auth/key/key.go
  auth/key/key_test.go
  auth/key/keybook.go
  auth/key/store.go
  auth/key/store_test.go
  auth/key/testdata/keystore.json
  auth/token/context.go
  auth/token/spec/token_store.go
  auth/token/token.go
  auth/token/token_test.go
  cmd/access.go
  cmd/access_test.go
  cmd/qri.go
  dscache/dscache_test.go
  dsref/mem_resolver_test.go
  dsref/spec/resolve.go
  lib/access.go
  lib/access_test.go
  lib/datasets_test.go
  lib/dispatch.go
  lib/fsi.go
  lib/http.go
  lib/lib.go
  lib/lib_test.go
  lib/scope.go
  lib/transform.go
  logbook/logbook.go
  p2p/resolve_ref_test.go
  profile/key.go
  profile/key_test.go
  profile/profile.go
  profile/store.go
  profile/store_test.go
  profile/testdata/simple.json
  remote/remote.go
  repo/buildrepo/build.go
Labels: access control, feat

#1678 feat(dispatch): Cursor for easy pagination
  api/fsi.go
  api/fsi_test.go
  cmd/checkout.go
  cmd/restore.go
  lib/access.go
  lib/datasets.go
  lib/datasets_test.go
  lib/dispatch.go
  lib/dispatch_test.go
  lib/fsi.go
  lib/fsi_test.go
  lib/test_runner_test.go
Labels: feat, lib

#1671 refactor(config): RPC > HTTP & API for config
  cmd/completion.go
  cmd/config.go
  lib/config.go
  lib/config_test.go
  lib/datasets_test.go
  lib/http.go
  lib/lib_test.go
  lib/rpc.go
Labels: API, RPC

#1682 lib.NewRequestHandler removes boilerplate from api package
  api/api.go
  api/api_test.go
  api/datasets.go
  api/datasets_test.go
  api/fsi.go
  api/fsi_test.go
  api/log.go
  lib/api.go
  lib/fsi.go
  lib/http.go
Labels: API

#1689 refactor(changes): use `Dispatch` with `lib.ChangeReport` function
  api/api.go
  api/datasets.go
  api/datasets_test.go
  changes/changes.go
  lib/changes.go
  lib/changes_test.go
  lib/datasets.go
  lib/diff.go
  lib/dispatch.go
  lib/fsi.go
  lib/scope.go
Labels: refactor

#1694 refactor(config): adjust `ConfigMethods` to use dispatch
  .gitignore
  api/api.go
  api/middleware.go
  cmd/completion.go
  cmd/config.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/qri.go
  lib/config.go
  lib/config_test.go
  lib/datasets.go
  lib/dispatch.go
  lib/lib.go
  lib/remote.go
  lib/resolve.go
  lib/scope.go
Labels: refactor

#1706 starlark ds.set_body infers missing structure component
  base/dataset_prepare.go
  base/dataset_prepare_test.go
  changes/changes_test.go
  go.mod
  go.sum
  lib/datasets.go
  lib/transform.go
  lib/transform_test.go
  transform/startf/ds/dataset.go
  transform/startf/ds/testdata/test.star
  transform/startf/exec_step.go
Labels: dataset, fix, starlark

#1701 refactor(dataset): dataset methods rely on `Dispatch`, for both lib & api
  api/datasets.go
  api/fsi_test.go
  api/log_test.go
  api/test_runner_test.go
  api/util/errors.go
  cmd/access.go
  cmd/apply.go
  cmd/checkout.go
  cmd/cmd_test.go
  cmd/completion.go
  cmd/config.go
  cmd/connect.go
  cmd/dag.go
  cmd/dag_test.go
  cmd/diff.go
  cmd/diff_test.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/fsi.go
  cmd/get.go
  cmd/get_test.go
  cmd/init.go
  cmd/list.go
  cmd/pull.go
  cmd/push.go
  cmd/qri.go
  cmd/remove.go
  cmd/remove_test.go
  cmd/rename.go
  cmd/rename_test.go
  cmd/restore.go
  cmd/save.go
  cmd/save_test.go
  cmd/stats.go
  cmd/stats_test.go
  cmd/status.go
  cmd/validate.go
  cmd/validate_test.go
  cmd/whatchanged.go
  lib/config.go
  lib/datasets.go
  lib/datasets_test.go
  lib/diff_test.go
  lib/integration_test.go
  lib/render_test.go
  lib/rpc_test.go
  lib/scope.go
  lib/test_runner_test.go
Labels: refactor

#1707 refactor(dataset): finish dataset dispatch refactor
  api/api.go
  api/datasets.go
  api/remote.go
  api/testdata/api.snapshot
  api/util/errors.go
  cmd/access.go
  cmd/checkout.go
  cmd/fsi.go
  cmd/init.go
  cmd/restore.go
  cmd/status.go
  cmd/whatchanged.go
  lib/api.go
  lib/datasets.go
  lib/datasets_test.go
  lib/integration_test.go
  lib/scope.go
  lib/test_runner_test.go
Labels: refactor

#1714 fix transform step duplication on save, CORS requests
  api/api.go
  api/middleware.go
  go.mod
  go.sum
Labels: API, fix, transforms

#1713 refactor(rpc): remove rpc
  api/api.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/peers.go
  cmd/qri.go
  lib/dispatch.go
  lib/http.go
  lib/lib.go
  lib/lib_test.go
  lib/rpc.go
  lib/rpc_test.go
Labels: RPC, refactor

#1708 refactor(diff): use `Dispatch` for `Diff` and `/diff`
  api/datasets.go
  config/test/config.go
  lib/datasets_test.go
  lib/diff.go
  lib/diff_test.go
  lib/fsi_test.go
  lib/lib.go
  lib/scope.go
  lib/test_runner_test.go
  repo/buildrepo/build.go
  repo/mem_repo.go
Labels: refactor

#1718 fix(api, token): dataset lib methods now working with http rpc
  auth/token/token.go
  auth/token/token_test.go
  cmd/print.go
  cmd/qri.go
  lib/access.go
  lib/dispatch.go
  lib/lib.go
  profile/store.go
Labels: fix

#1719 refactor(api): adjust dataset request handlers to more up-to-date api patterns
  api/api.go
  api/api_test.go
  api/datasets.go
  api/datasets_test.go
  api/fsi_test.go
  cmd/print.go
  lib/api.go
  lib/dispatch.go
  lib/http.go
  p2p/dag.go
Labels: refactor

#1724 refactor(lib): convert peer methods to use Dispatch pattern
  api/api.go
  api/api_test.go
  api/peers.go
  api/peers_test.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/peers.go
  cmd/qri.go
  lib/api.go
  lib/dispatch.go
  lib/lib.go
  lib/peers.go
  lib/peers_test.go
Labels: refactor

#1726 feat(dispatch): Abs paths on inputs to dispatch methods
  cmd/checkout.go
  cmd/save.go
  cmd/save_test.go
  fsi/init.go
  lib/datasets.go
  lib/diff.go
  lib/dispatch.go
  lib/fsi.go
  lib/fsi_test.go
  lib/params.go
  lib/params_test.go
Labels: RPC
