Repository qri-io/qri, pull requests merged in 2021-05, with the labels that each got.

#1781 chore(spec): generate latest open api spec
  api/open_api_3.yaml
Labels: API, chore

#1782 chore(release): release v0.10.0
  CHANGELOG.md
  Makefile
Labels: chore

#1795 feat(automation): add `Orchestrator` that manages workflow automation
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/run/run.go
  automation/run/run_test.go
  automation/workflow/workflow.go
  base/save.go
  cmd/test_runner_test.go
  event/workflow.go
  lib/automation.go
  lib/datasets.go
  logbook/logbook.go
  transform/apply_test.go
Labels: feat

#1799 chore(deps): update flock
  auth/key/store.go
  go.mod
  profile/store.go
Labels: chore

#1738 collection spec test
  base/params/list.go
  collection/collection.go
  collection/collection_test.go
  collection/spec/collection.go
  dsref/version_info.go
  dsref/version_info_test.go
  profile/test/profiles.go
Labels: spec, test
