Repository qri-io/qri, pull requests merged in 2021-01, with the labels that each got.

#1603 feat(apply): Apply command, and `qri save --apply`
  api/api.go
  api/datasets.go
  api/datasets_test.go
  api/testdata/api.snapshot
  api/transform.go
  base/body.go
  base/revisions.go
  base/revisions_test.go
  base/transform_apply.go
  cmd/apply.go
  cmd/apply_test.go
  cmd/cmd_test.go
  cmd/factory.go
  cmd/factory_test.go
  cmd/qri.go
  cmd/save.go
  cmd/save_test.go
  lib/datasets.go
  lib/datasets_test.go
  lib/integration_test.go
  lib/lib_test.go
  lib/test_runner_test.go
  lib/testdata/cities_2/add_city.star
  lib/transform.go
  lib/transform_test.go
Labels: feat

#1605 fix(dsfs): LoadDataset using the mux filesystem. Error if nil
  base/dsfs/dataset.go
  lib/load.go
Labels: fix

#1610 refactor(transform): Create transform package, move startf into it
  cmd/test_runner_test.go
  lib/datasets.go
  lib/transform.go
  transform/apply.go
  transform/startf/README.md
  transform/startf/context/context.go
  transform/startf/context/context_test.go
  transform/startf/context/testdata/test.star
  transform/startf/ds/dataset.go
  transform/startf/ds/dataset_test.go
  transform/startf/ds/doc.go
  transform/startf/ds/entry_reader.go
  transform/startf/ds/entry_reader_test.go
  transform/startf/ds/entry_writer.go
  transform/startf/ds/testdata/test.star
  transform/startf/entry_reader.go
  transform/startf/entry_reader_test.go
  transform/startf/qri/entry_writer.go
  transform/startf/qri/qri.go
  transform/startf/qri/qri_test.go
  transform/startf/qri/testdata/test.star
  transform/startf/sandbox.go
  transform/startf/testdata/fetch.star
  transform/startf/testdata/load_ds.star
  transform/startf/testdata/meta_title.star
  transform/startf/testdata/tf.star
  transform/startf/transform.go
  transform/startf/transform_test.go
Labels: refactor

#1615 refactor(api): adjust `Server` & middleware funcs to make the qri api more extensible by outside packages
  api/api.go
  api/middleware.go
Labels: refactor

#1614 feat(event): Subscribe by event topic, id, or to all
  base/dsfs/dataset_test.go
  cmd/print.go
  dscache/dscache.go
  event/event.go
  event/event_test.go
  lib/datasets.go
  lib/lib.go
  lib/lib_test.go
  lib/transform.go
  lib/websocket.go
  p2p/node_test.go
  p2p/profile_service_test.go
  p2p/resolve_ref_test.go
  remote/remote_test.go
  transform/apply.go
  watchfs/watchfs.go
  watchfs/watchfs_test.go
Labels: event bus, feat

#1616 fix(repo): Don't use blank path for new repo in tests
  key/store.go
  lib/lib.go
  profile/store.go
  repo/buildrepo/build.go
Labels: fix, test

#1623 feature(transform): Transform step execution
  event/transform.go
  lib/datasets.go
  lib/transform.go
  transform/apply.go
  transform/apply_test.go
  transform/startf/exec_step.go
  transform/startf/transform.go
  transform/startf/transform_test.go
Labels: event bus, feat, transforms

#1625 fix(transform): don't write to out streams when nil, use updated preview.Create
  go.mod
  lib/datasets.go
  lib/transform.go
  remote/browse.go
  transform/startf/exec_step.go
Labels: fix, transforms
