Repository qri-io/qri, pull requests merged in 2021-07, with the labels that each got.

#1827 docs(api): add serve-api-docs make command to watch & serve docs
  Makefile
  docs/api_docs.go
  docs/docs.go
  docs/go.mod
  docs/go.sum
  docs/http.go
Labels: docs

#1828 Support docs examples from source comments, add json struct tags to lib input parameters
  docs/api_doc_template.yaml
  docs/api_docs.go
  docs/docs.go
  lib/access.go
  lib/automation.go
  lib/datasets.go
  lib/fsi.go
  lib/params.go
  lib/peers.go
  lib/profile.go
  lib/remote.go
  lib/sql.go
Labels: docs, fix, lib

#1829 chore(makefile): Get minimum go version from go.mod
  Makefile
Labels: fix

#1832 documenting method & struct params
  docs/api_doc_template.yaml
  docs/api_docs.go
  lib/access.go
  lib/collection.go
  lib/datasets.go
  lib/params.go
Labels: API, chore, docs

#1833 docs(api): add types from dataset & dsref packages
  .circleci/config.yml
  docs/api_doc_template.yaml
  docs/api_docs.go
Labels: API, docs

#1831 feat(get): Limit size of body that `get` may return when using `all`
  lib/datasets.go
  lib/datasets_test.go
Labels: feat

#1834 feat(resolver): resolving a reference w an initID completes the ref
  base/dataset_prepare.go
  cmd/save_test.go
  dscache/dscache.go
  dsref/mem_resolver.go
  dsref/spec/resolve.go
  logbook/logbook.go
  remote/client.go
  remote/server.go
  repo/fs/fs.go
Labels: feat, resolvers

#1822 feat(automation): expand Orchestrator methods
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/spec/trigger.go
  automation/spec/workflow_store.go
  automation/trigger/runtime.go
  automation/trigger/runtime_test.go
  automation/trigger/trigger.go
  automation/workflow/store.go
  automation/workflow/workflow.go
  base/save.go
  event/automation.go
  event/workflow.go
  lib/api.go
  lib/automation.go
  lib/automation_test.go
  lib/lib.go
  lib/scope.go
  profile/context.go
Labels: feat, refactor

#1835 fix(lib): adjust `Deploy` scope
  lib/automation.go
Labels: automation

#1836 fix(event): add json tags to automation event payloads
  event/automation.go
Labels: fix

#1837 refactor(starlark): Convert Dataset to a true starlark.Value
  transform/startf/ds/dataset.go
  transform/startf/ds/dataset_test.go
  transform/startf/exec_step.go
  transform/startf/transform.go
Labels: refactor

#1838 feat(trigger): Add `CronListener` and `CronTriggers`
  api/api.go
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/spec/trigger.go
  automation/trigger/cron.go
  automation/trigger/cron_test.go
  automation/trigger/runtime.go
  automation/trigger/runtime_test.go
  automation/trigger/trigger.go
  automation/trigger/trigger_test.go
  go.mod
  go.sum
  lib/lib.go
Labels: feat

#1843 use new collection subsystem locally
  api/http_client_test.go
  api/testdata/http_client/list.json
  base/dataset.go
  base/dataset_prepare.go
  base/dataset_prepare_test.go
  base/dataset_test.go
  base/log_test.go
  base/test_runner_test.go
  cmd/cmd_test.go
  cmd/fsi_integration_test.go
  cmd/pull_test.go
  cmd/remove_integration_test.go
  cmd/rename_integration_test.go
  cmd/test_runner_test.go
  collection/collection.go
  collection/migrate.go
  collection/migrate_test.go
  collection/spec/collection.go
  dscache/convert_test.go
  dscache/dscache.go
  dsref/spec/resolve.go
  dsref/version_info.go
  event/dataset.go
  event/filesystem.go
  event/remote.go
  fsi/fsi.go
  fsi/fsi_test.go
  fsi/init.go
  fsi/watchfs/watchfs.go
  lib/collection.go
  lib/integration_test.go
  lib/lib.go
  lib/load_test.go
  lib/registry.go
  logbook/logbook.go
  logbook/logbook_test.go
  logbook/logsync/logsync_test.go
  logbook/temp_builder.go
  registry/regclient/client_test.go
  registry/regserver/mock.go
  remote/client.go
  remote/mock/client.go
  remote/registry/regclient/client_test.go
  remote/registry/regserver/mock.go
  remote/remote_test.go
  remote/server.go
  repo/test/test_repo.go
Labels: collection, event bus, feat

#1847 feat(run, workflow): add file store implementations of `workflow.Store` and `run.Store`
  automation/orchestrator.go
  automation/run/filestore.go
  automation/run/filestore_test.go
  automation/run/run.go
  automation/run/store.go
  automation/workflow/filestore.go
  automation/workflow/filestore_test.go
  automation/workflow/store.go
  lib/lib.go
Labels: feat

#1848 refactor(run): rename `StepState` deserialization object
  automation/run/run.go
Labels: refactor

#1853 fix(automation): update `Listeners` after the `Workflow` has been changed
  automation/orchestrator.go
  automation/orchestrator_test.go
  automation/trigger/cron.go
  automation/trigger/cron_test.go
Labels: fix
